<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-Hans" xml:lang="zh-Hans"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="NVIDIA, GPU, Microarchitecture, Simulation">
<meta name="description" content="原文：Analyzing Modern NVIDIA GPU cores">

<title>Analyzing Modern NVIDIA GPU cores – 悲催的袜子</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-39cdd0f1bff0c792356829953f17b6ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "没有结果",
    "search-matching-documents-text": "匹配的文档",
    "search-copy-link-title": "复制搜索链接",
    "search-hide-matches-text": "隐藏其它匹配结果",
    "search-more-match-text": "更多匹配结果",
    "search-more-matches-text": "更多匹配结果",
    "search-clear-button-title": "清除",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "取消",
    "search-submit-button-title": "提交",
    "search-label": "搜索"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">悲催的袜子</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="搜索"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="展开或折叠导航栏" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">主页</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">关于</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">该页面内容</h2>
   
  <ul>
  <li><a href="#sec-introduction" id="toc-sec-introduction" class="nav-link active" data-scroll-target="#sec-introduction">引言</a></li>
  <li><a href="#sec-backgroundmotivation" id="toc-sec-backgroundmotivation" class="nav-link" data-scroll-target="#sec-backgroundmotivation">背景与动机</a></li>
  <li><a href="#sec-researchmethodology" id="toc-sec-researchmethodology" class="nav-link" data-scroll-target="#sec-researchmethodology">逆向方法</a></li>
  <li><a href="#sec-moderngpuarch" id="toc-sec-moderngpuarch" class="nav-link" data-scroll-target="#sec-moderngpuarch">现代 NVIDIA GPU 架构中的控制位</a></li>
  <li><a href="#sec-design" id="toc-sec-design" class="nav-link" data-scroll-target="#sec-design">GPU 核心微架构</a>
  <ul class="collapse">
  <li><a href="#sec-warpscheduler" id="toc-sec-warpscheduler" class="nav-link" data-scroll-target="#sec-warpscheduler">发射调度器</a>
  <ul class="collapse">
  <li><a href="#sec-readinesschecking" id="toc-sec-readinesschecking" class="nav-link" data-scroll-target="#sec-readinesschecking">Warp 就绪条件</a></li>
  <li><a href="#sec-schedulingpolicy" id="toc-sec-schedulingpolicy" class="nav-link" data-scroll-target="#sec-schedulingpolicy">调度策略</a></li>
  </ul></li>
  <li><a href="#sec-frontend" id="toc-sec-frontend" class="nav-link" data-scroll-target="#sec-frontend">前端</a></li>
  <li><a href="#sec-regfile" id="toc-sec-regfile" class="nav-link" data-scroll-target="#sec-regfile">寄存器文件</a>
  <ul class="collapse">
  <li><a href="#sec-reg-file-cache" id="toc-sec-reg-file-cache" class="nav-link" data-scroll-target="#sec-reg-file-cache">寄存器文件缓存</a></li>
  </ul></li>
  <li><a href="#sec-memory-pipeline" id="toc-sec-memory-pipeline" class="nav-link" data-scroll-target="#sec-memory-pipeline">内存流水线</a></li>
  </ul></li>
  <li><a href="#sec-modeling" id="toc-sec-modeling" class="nav-link" data-scroll-target="#sec-modeling">建模</a></li>
  <li><a href="#sec-validation" id="toc-sec-validation" class="nav-link" data-scroll-target="#sec-validation">验证</a>
  <ul class="collapse">
  <li><a href="#sec-methodoloy" id="toc-sec-methodoloy" class="nav-link" data-scroll-target="#sec-methodoloy">方法</a></li>
  <li><a href="#sec-cycle-accuracy" id="toc-sec-cycle-accuracy" class="nav-link" data-scroll-target="#sec-cycle-accuracy">性能准确性</a></li>
  <li><a href="#sec-results-instruction-prefetching" id="toc-sec-results-instruction-prefetching" class="nav-link" data-scroll-target="#sec-results-instruction-prefetching">指令预取的敏感性分析</a></li>
  <li><a href="#sec-eval-rf" id="toc-sec-eval-rf" class="nav-link" data-scroll-target="#sec-eval-rf">寄存器文件架构的敏感性分析</a></li>
  <li><a href="#sec-deps-analysis" id="toc-sec-deps-analysis" class="nav-link" data-scroll-target="#sec-deps-analysis">依赖管理机制分析</a></li>
  <li><a href="#sec-use-other-archs" id="toc-sec-use-other-archs" class="nav-link" data-scroll-target="#sec-use-other-archs">向其他 NVIDIA 架构的可移植性</a></li>
  </ul></li>
  <li><a href="#sec-relatedwork" id="toc-sec-relatedwork" class="nav-link" data-scroll-target="#sec-relatedwork">相关工作</a></li>
  <li><a href="#sec-conclusion" id="toc-sec-conclusion" class="nav-link" data-scroll-target="#sec-conclusion">结论</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyzing Modern NVIDIA GPU cores</h1>
  <div class="quarto-categories">
    <div class="quarto-category">翻译</div>
    <div class="quarto-category">Architecture</div>
  </div>
  </div>

<div>
  <div class="description">
    原文：Analyzing Modern NVIDIA GPU cores
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">发布于</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2026年3月3日</p>
    </div>
  </div>
  
    
  </div>
  

<div>
  <div class="keywords">
    <div class="block-title">关键词</div>
    <p>NVIDIA, GPU, Microarchitecture, Simulation</p>
  </div>
</div>

</header>


<section id="sec-introduction" class="level1">
<h1>引言</h1>
<p>近年来，GPU 已不仅用于图形渲染，也被广泛用于通用计算负载<span class="citation" data-cites="usageOfGPUs"><a href="#ref-usageOfGPUs" role="doc-biblioref">[1]</a></span>。GPU 架构提供的大规模并行性可被许多现代应用充分利用，例如生物信息学<span class="citation" data-cites="cudaInGPUS markovGPUBioinformatics"><a href="#ref-cudaInGPUS" role="doc-biblioref">[2]</a>, <a href="#ref-markovGPUBioinformatics" role="doc-biblioref">[3]</a></span>、物理模拟<span class="citation" data-cites="molecularPhysicsCuda fdtdPhysicsCuda"><a href="#ref-molecularPhysicsCuda" role="doc-biblioref">[4]</a>, <a href="#ref-fdtdPhysicsCuda" role="doc-biblioref">[5]</a></span>、化学计算<span class="citation" data-cites="detailedChemistry cheminformaticsGPU"><a href="#ref-detailedChemistry" role="doc-biblioref">[6]</a>, <a href="#ref-cheminformaticsGPU" role="doc-biblioref">[7]</a></span>等。如今，GPU 是加速现代机器学习工作负载的核心平台，这些工作负载对内存带宽与计算能力的需求极高<span class="citation" data-cites="cuDNNLibraryIA"><a href="#ref-cuDNNLibraryIA" role="doc-biblioref">[8]</a></span>。近年来 GPU 微架构、互连技术（如 NVLink<span class="citation" data-cites="nvlink"><a href="#ref-nvlink" role="doc-biblioref">[9]</a></span>）与通信框架（如 NCCL<span class="citation" data-cites="nccl"><a href="#ref-nccl" role="doc-biblioref">[10]</a></span>）持续演进，这些进步使得需要数千块 GPU 的大语言模型训练与推理成为可能<span class="citation" data-cites="articuloWebMSNumGPUsIA"><a href="#ref-articuloWebMSNumGPUsIA" role="doc-biblioref">[11]</a></span>。</p>
<p>然而，现代商业 GPU 的微架构细节信息十分稀缺，学术研究中常用的模型仍以 2006 年发布的 Tesla 架构为基线<span class="citation" data-cites="gpgpusim3 accelsim teslaHotchips"><a href="#ref-gpgpusim3" role="doc-biblioref">[12]</a>, <a href="#ref-accelsim" role="doc-biblioref">[13]</a>, <a href="#ref-teslaHotchips" role="doc-biblioref">[14]</a></span>。现代 GPU 相比 Tesla 已发生了显著变化，基于旧架构的模型可能导致结论偏差。本文旨在揭示现代 NVIDIA GPU 架构中的关键特性与组件细节，以提升学术界 GPU 微架构模型的准确性，从而帮助研究者更好地识别未来 GPU 的挑战与机会。本文的主要贡献如下：</p>
<ul>
<li>描述发射阶段的运行机制，包括依赖处理、warp 就绪条件以及发射调度策略。</li>
<li>描述一种可信的取指阶段与其调度器，并说明其与发射阶段的协调方式。</li>
<li>给出寄存器文件的重要细节并解释寄存器文件缓存的行为，表明现代 NVIDIA GPU 不使用 operand collection 阶段或 collector units。</li>
<li>揭示内存流水线的多项细节。</li>
<li>重新设计 Accel-Sim 模拟器中的 SM/Core 模型，并整合本文揭示的全部细节。</li>
<li>将新模型与真实硬件进行验证并与 Accel-Sim 对比。对 NVIDIA RTX A6000（Ampere）而言，我们的新模型在执行周期上的 MAPE 为 13.98%，比旧模型提升 18.24%。</li>
<li>证明基于流缓冲的朴素指令预取在性能精度上优于预期，效果接近“完美指令缓存”。</li>
<li>分析寄存器文件缓存和寄存器文件读端口数量对仿真精度与性能的影响。</li>
<li>比较本文揭示的依赖管理机制与传统记分牌方法在性能、面积与仿真精度上的差异，表明这种软硬协同设计更高效。</li>
<li>证明模型对 NVIDIA 其他架构（如 Turing）的可移植性。</li>
</ul>
<p>本文其余部分结构如下：第 <a href="#sec-backgroundmotivation" class="quarto-xref">小节&nbsp;2</a> 节介绍背景与动机；第 <a href="#sec-researchmethodology" class="quarto-xref">小节&nbsp;3</a> 节说明逆向方法；第 <a href="#sec-moderngpuarch" class="quarto-xref">小节&nbsp;4</a> 节描述现代 NVIDIA GPU 的控制位（control bits）及其行为；第 <a href="#sec-design" class="quarto-xref">小节&nbsp;5</a> 节呈现 GPU 核心微架构；第 <a href="#sec-modeling" class="quarto-xref">小节&nbsp;6</a> 节描述仿真模型；第 <a href="#sec-validation" class="quarto-xref">小节&nbsp;7</a> 节评估模型准确性并分析指令预取、寄存器文件缓存与依赖管理机制等因素；第 <a href="#sec-relatedwork" class="quarto-xref">小节&nbsp;8</a> 节回顾相关工作；最后第 <a href="#sec-conclusion" class="quarto-xref">小节&nbsp;9</a> 节总结全文。</p>
</section>
<section id="sec-backgroundmotivation" class="level1">
<h1>背景与动机</h1>
<p>学术界对 GPU 微架构的研究多依赖 GPGPU-Sim 模拟器所采用的模型<span class="citation" data-cites="gpgpusim3 gpgpuBook"><a href="#ref-gpgpusim3" role="doc-biblioref">[12]</a>, <a href="#ref-gpgpuBook" role="doc-biblioref">[15]</a></span>。该模拟器近年来更新为包含 Volta 起引入的 sub-core（NVIDIA 术语为 Processing Blocks）方案。<a href="#fig-academia" class="quarto-xref">图&nbsp;1</a> 展示了该模型的架构示意图，可以看到其包含四个 sub-core 以及若干共享组件，如 L1 指令缓存、L1 数据缓存、共享内存与纹理单元。</p>
<div id="fig-academia" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-academia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/modern-nvidia-gpu/Rev_literature.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-academia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;1: 学术界常用的 SM/Core 设计示意。
</figcaption>
</figure>
</div>
<p>在该 GPU 流水线的取指阶段，轮转调度器会选择一个 warp，其下一条指令位于 L1 指令缓存且其指令缓冲区有空位。每个 warp 维护一个独占的指令缓冲区，用于存放取指与译码后的连续指令，直到这些指令就绪并被发射。</p>
<p>在发射阶段，采用 GTO（Greedy Then Oldest）调度器<span class="citation" data-cites="GTO"><a href="#ref-GTO" role="doc-biblioref">[16]</a></span>，只要 warp 不在等待 barrier 且其最老指令与流水线中的更早指令无数据依赖，就会被发射。以往工作通常假设每个 warp 有两个记分牌用于依赖检测：第一个记录寄存器待写入以追踪 WAW 与 RAW，只有当所有源操作数在该记分牌中清零时指令才可发射；第二个记分牌统计寄存器的在途消费者数量，用于防止 WAR 冒险<span class="citation" data-cites="warHazards"><a href="#ref-warHazards" role="doc-biblioref">[17]</a></span>。第二个记分牌的必要性在于：虽然指令按序发射，但由于可变延迟指令（如内存指令）可能在发射后排队，其源操作数的读取可能晚于更年轻指令的写回，导致 WAR 冒险。</p>
<p>指令发射后进入 Collector Unit（CU），等待源寄存器操作数就绪。每个 sub-core 的私有寄存器文件由多个 bank 组成，每个 bank 有若干端口以在单周期内支持多次访问；仲裁器负责处理同一 bank 的并发访问冲突。当指令的所有源操作数都在 CU 中就绪后，进入 Dispatch 阶段并派发到对应的执行单元（如内存、单精度、特殊函数单元）。不同单元的延迟各不相同，写回阶段将结果写入寄存器文件。</p>
<p>Accel-Sim 所建模的 GPU 架构类似基于 Tesla 的 NVIDIA GPU<span class="citation" data-cites="teslaHotchips"><a href="#ref-teslaHotchips" role="doc-biblioref">[14]</a></span>，该架构发布于 2006 年，并仅做了少量现代化更新（例如 sub-core 模型与类似 Volta 的分区缓存与 IPOLY 索引<span class="citation" data-cites="accelsim IPOLYPaper"><a href="#ref-accelsim" role="doc-biblioref">[13]</a>, <a href="#ref-IPOLYPaper" role="doc-biblioref">[18]</a></span>）。但该模型缺少现代 NVIDIA GPU 中存在的关键组件，例如 L0 指令缓存<span class="citation" data-cites="voltaPaper turingPaper amperePaper hopperPaper adaPaper voltaHotChips turingHotChips"><a href="#ref-voltaPaper" role="doc-biblioref">[19]</a>, <a href="#ref-turingPaper" role="doc-biblioref">[20]</a>, <a href="#ref-amperePaper" role="doc-biblioref">[21]</a>, <a href="#ref-hopperPaper" role="doc-biblioref">[22]</a>, <a href="#ref-adaPaper" role="doc-biblioref">[23]</a>, <a href="#ref-voltaHotChips" role="doc-biblioref">[24]</a>, <a href="#ref-turingHotChips" role="doc-biblioref">[25]</a></span>与统一寄存器文件<span class="citation" data-cites="turingHotChips"><a href="#ref-turingHotChips" role="doc-biblioref">[25]</a></span>。此外，sub-core 中的多个关键组件（如发射逻辑、寄存器文件、寄存器文件缓存）并未更新以反映当前设计。</p>
<p>本文旨在逆向现代 NVIDIA GPU 的核心微架构，并更新 Accel-Sim 以纳入这些新特性，从而让该模拟器的基线更贴近工业界已验证的商业设计。</p>
</section>
<section id="sec-researchmethodology" class="level1">
<h1>逆向方法</h1>
<p>本节阐述我们用于发现 NVIDIA Ampere GPU 核心（SM）微架构的研究方法。</p>
<p>我们的做法是编写由少量指令组成的 microbenchmarks，通过测量一段特定指令序列的执行时间来推断微架构特性。具体做法是：在代码段前后插入读取 GPU <code>CLOCK</code> 计数器的指令，将计数器保存到寄存器并写入主存，便于后续分析。被测指令序列通常由手写 SASS 指令及其控制位构成。根据测试需求，我们对记录的周期进行可视化，以验证或否定某一控制位语义或微架构特性。以下是两个示例：</p>
<ul>
<li>使用下面代码揭示多 bank 寄存器文件的读冲突（见 <a href="#sec-regfile" class="quarto-xref">小节&nbsp;5.3</a>）。若将 <code>R_X</code> 与 <code>R_Y</code> 都设为奇数（例如 <code>R19</code> 和 <code>R21</code>），耗时为 5 个周期（每 sub-core 每周期可发射一条指令的理论最小值）。若将 <code>R_X</code> 改为偶数（如 <code>R18</code>）而 <code>R_Y</code> 仍为奇数（如 <code>R21</code>），耗时变为 6 个周期；若两个操作数均为偶数（如 <code>R18</code> 与 <code>R20</code>），耗时为 7 个周期。也就是说，两条连续指令之间可能出现 0 到 2 个气泡（bubble），取决于寄存器选择。</li>
<li><a href="#fig-issue-scheduling-timeline" class="quarto-xref">图&nbsp;4</a> 展示了多次记录的时间标记在图形上的体现，用于揭示 warp 发射策略（详见 <a href="#sec-schedulingpolicy" class="quarto-xref">小节&nbsp;5.1.2</a>）。</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 用于检查寄存器文件读冲突的代码</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>CLOCK</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>NOP</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>FFMA R11, R10, R12, R14</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>FFMA R13, R16, R_X, R_Y</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>NOP</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>CLOCK</span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
<p>尽管 NVIDIA 没有官方工具可直接编写 SASS（NVIDIA 汇编语言），但已有多种第三方工具支持重排与修改汇编指令（包括控制位），常用于优化关键内核。MaxAS<span class="citation" data-cites="maxas"><a href="#ref-maxas" role="doc-biblioref">[26]</a></span> 是最早的 SASS 修改工具；随后 KeplerAS<span class="citation" data-cites="KeplerASRepo KeplerASPaper"><a href="#ref-KeplerASRepo" role="doc-biblioref">[27]</a>, <a href="#ref-KeplerASPaper" role="doc-biblioref">[28]</a></span> 针对 Kepler 架构出现；之后 TuringAS<span class="citation" data-cites="turingas"><a href="#ref-turingas" role="doc-biblioref">[29]</a></span> 与 CUAssembler<span class="citation" data-cites="CuAssembler"><a href="#ref-CuAssembler" role="doc-biblioref">[30]</a></span> 支持更新架构。我们选择 CUAssembler，因为它具有更高的灵活性、可扩展性，并支持最新硬件。</p>
</section>
<section id="sec-moderngpuarch" class="level1">
<h1>现代 NVIDIA GPU 架构中的控制位</h1>
<p>现代 NVIDIA GPU 的 ISA 包含控制位，编译器借此保证正确性并优化性能。与以往在运行时追踪寄存器读写以处理数据依赖的架构不同（见 <a href="#sec-backgroundmotivation" class="quarto-xref">小节&nbsp;2</a>），现代 NVIDIA GPU 依赖编译器管理寄存器数据依赖<span class="citation" data-cites="gtx680WhitePaper"><a href="#ref-gtx680WhitePaper" role="doc-biblioref">[31]</a></span>。因此，每条汇编指令都携带控制位用于依赖管理、性能与能耗优化。</p>
<p>下文描述每条指令中的控制位行为。我们的解释参考了多份文档<span class="citation" data-cites="dissectingVolta dissectingTuring CuAssembler maxas"><a href="#ref-maxas" role="doc-biblioref">[26]</a>, <a href="#ref-CuAssembler" role="doc-biblioref">[30]</a>, <a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>，但这些文档常不完整或存在歧义，因此我们结合 <a href="#sec-researchmethodology" class="quarto-xref">小节&nbsp;3</a> 的方法来验证这些控制位的语义。</p>
<p>sub-core 每周期最多发射一条指令。默认情况下，发射调度器倾向于从同一 warp 发射指令，只要该 warp 中程序顺序最老的指令已就绪。编译器通过控制位标记指令何时可发射；若上一周期被选中的 warp 的最老指令未就绪，则发射逻辑按照 <a href="#sec-warpscheduler" class="quarto-xref">小节&nbsp;5.1</a> 描述的策略从其他 warp 中选择。</p>
<p>对于固定延迟指令的生产者—消费者依赖，每个 warp 有一个称为“停顿计数器（Stall counter）”的计数器。若该计数器非零，则该 warp 不可发射。编译器将“生产者指令的延迟 - 生产者与首个消费者之间的指令数”写入停顿计数器。所有 warp 的停顿计数器每周期减 1，直到为 0；发射逻辑仅需检查该计数器即可判断是否可从同一 warp 继续发射。</p>
<p>例如，一条延迟为 4 周期的加法指令，且其首个消费者是下一条指令，则停顿计数器被设为 4。我们验证了如果停顿计数器设置不正确，程序结果会出错，因为硬件不检查 RAW 冒险，而完全依赖编译器设置的计数器。该机制也节省面积与布线能耗，因为固定延迟单元到依赖处理逻辑的连线不再需要，而传统记分牌方案则需要这些连线。</p>
<p>另一个控制位是“Yield”，用于告知硬件下一周期不要从同一 warp 发射指令。如果其他 warp 也未就绪，则该周期不会发射任何指令。</p>
<p>每条指令都会设置停顿计数器与 Yield 位。当停顿计数器大于 1 时，warp 至少停顿一个周期，此时无论 Yield 是否置位均无影响。</p>
<p>另一方面，部分指令（如内存或特殊函数）具有可变延迟，编译器无法预知其执行时间，因此不能仅靠停顿计数器处理。这类冒险通过“依赖计数器（Dependence counters）”解决。每个 warp 有 6 个专用寄存器（<code>SB0</code> 到 <code>SB5</code>），每个计数器可计数至 63。</p>
<p>这些计数器在 warp 启动时置零。对于生产者—消费者依赖，生产者在发射后增加某计数器，并在写回时减小；消费者指令会等待该计数器归零后才能发射。</p>
<p>对于 WAR 冒险，机制类似，但计数器在读取源操作数后减小，而非在写回时减小。</p>
<p>每条指令的控制位可以指明最多两个在发射时递增的计数器，其中一个在写回时递减（用于 RAW/WAW），另一个在寄存器读取时递减（用于 WAR）。为此，每条指令有两个 3 位字段用于指示这两个计数器，并有一个 6 位掩码，用于指定该指令在发射前需要检查哪些依赖计数器（最多可检查 6 个）。</p>
<p>如果一条指令有多个源操作数且其生产者均为可变延迟指令，那么这些生产者可共用同一个依赖计数器而不降低并行性。但当存在超过 6 个不同可变延迟生产者时，会受到并行度限制，编译器需在“合并计数器”与“重排指令”之间权衡。</p>
<p>依赖计数器的自增发生在生产者发射后的下一周期，因此不会在当周期生效。如果消费者紧随其后，则生产者需要将停顿计数器设为 2，以避免下一周期错误发射消费者指令。</p>
<div id="fig-control-bits-example" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-control-bits-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/modern-nvidia-gpu/Rev_ControlBitsExample.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-control-bits-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;2: 使用依赖计数器处理依赖的示例。
</figcaption>
</figure>
</div>
<p>如 <a href="#fig-control-bits-example" class="quarto-xref">图&nbsp;2</a> 所示，该代码包含四条指令（3 条 load 与 1 条 add）及其编码。由于 add 依赖于可变延迟的 load，需依赖计数器避免数据冒险。PC 为 <code>0x80</code> 的指令对 <code>0x50</code> 与 <code>0x60</code> 存在 RAW 依赖，因此 <code>SB3</code> 在 <code>0x50</code> 与 <code>0x60</code> 发射时增加，在写回时减少。另一方面，add 对 <code>0x60</code> 与 <code>0x70</code> 有 WAR 依赖，于是 <code>SB0</code> 在 <code>0x60</code> 与 <code>0x70</code> 发射时增加，在读取源操作数后减少。add 的依赖计数器掩码要求 <code>SB0</code> 与 <code>SB3</code> 在发射前均为 0。注意 <code>0x70</code> 还使用 <code>SB4</code> 控制与后续指令的 RAW/WAR 冒险，但 <code>0x80</code> 与该 load 无依赖，因此不等待 <code>SB4</code>。在读取源操作数后清除 WAR 依赖是重要的优化，因为源操作数往往在结果写回之前很早就已读取，尤其在内存指令中更为明显。</p>
<p>另一种检查计数器就绪性的方式是使用 <code>DEPBAR.LE</code> 指令。例如，<code>DEPBAR.LE SB1, 0x3, {4,3,2}</code> 要求依赖计数器 <code>SB1</code> 的值小于等于 3 才能继续执行；最后一个参数是可选项，如果使用，则该指令还要求指定的依赖计数器（例中为 4、3、2）全部为 0 才能发射。</p>
<p><code>DEPBAR.LE</code> 在某些场景非常有用。例如，当有一串 <code>N</code> 条可变延迟指令按序写回（如带 <code>STRONG.SM</code> 的内存指令），而消费者只需等待前 <code>M</code> 条指令完成时，可设置 <code>DEPBAR.LE</code> 的参数为 <code>N-M</code> 来等待前 <code>M</code> 条。另一个例子是复用同一依赖计数器来同时保护 RAW/WAW 与 WAR：由于 WAR 先于 RAW/WAW 解决，后续的 <code>DEPBAR.LE SBx, 0x1</code> 可等待 WAR 解除并继续执行，而真正的消费者则等待计数器归零以确保结果写回。</p>
<p>此外，GPU 还使用寄存器文件缓存（RFC）以节能并减少寄存器文件读端口竞争。该结构由软件管理：每个源操作数都有一个 <code>reuse</code> 控制位，指示硬件是否缓存该寄存器内容。RFC 的组织细节见 <a href="#sec-reg-file-cache" class="quarto-xref">小节&nbsp;5.3.1</a>。</p>
<p>最后，虽然本文聚焦 NVIDIA 架构，但 AMD GPU ISA 的公开文档<span class="citation" data-cites="amdCDNA1 amdCDNA2 amdCDNA3 amdRDNA1 amdRDNA2 amdRDNA35 amdRDNA3 amdVega7nm amdGCN3 amdVega"><a href="#ref-amdCDNA1" role="doc-biblioref">[34]</a>, <a href="#ref-amdCDNA2" role="doc-biblioref">[35]</a>, <a href="#ref-amdCDNA3" role="doc-biblioref">[36]</a>, <a href="#ref-amdRDNA1" role="doc-biblioref">[37]</a>, <a href="#ref-amdRDNA2" role="doc-biblioref">[38]</a>, <a href="#ref-amdRDNA35" role="doc-biblioref">[39]</a>, <a href="#ref-amdRDNA3" role="doc-biblioref">[40]</a>, <a href="#ref-amdVega7nm" role="doc-biblioref">[41]</a>, <a href="#ref-amdGCN3" role="doc-biblioref">[42]</a>, <a href="#ref-amdVega" role="doc-biblioref">[43]</a></span> 显示 AMD 同样依赖软硬协同机制管理依赖、提升性能。类似 NVIDIA 的 <code>DEPBAR.LE</code>，AMD 使用 <code>waitcnt</code> 指令；根据架构，每个 wavefront（warp）有 3 或 4 个计数器，且每个计数器绑定特定指令类型并必须使用以避免相关冒险。AMD 不允许普通指令通过控制位等待计数器归零，必须显式插入 <code>waitcnt</code>，这增加了指令数量。该设计降低了解码开销，但提高了指令数。相比之下，NVIDIA 提供更多计数器且不与指令类型绑定，因此可在同一指令类型内部保持更多并发依赖链。虽然 AMD 的 ALU 指令不需要软件或编译器干预即可避免冒险，但在 RDNA 3/3.5 中引入了 <code>DELAY_ALU</code> 以缓解依赖导致的流水线停顿<span class="citation" data-cites="amdRDNA35 amdRDNA3"><a href="#ref-amdRDNA35" role="doc-biblioref">[39]</a>, <a href="#ref-amdRDNA3" role="doc-biblioref">[40]</a></span>。而 NVIDIA 则依赖编译器为固定延迟指令正确设置停顿计数器，以较少的指令数换取更高的解码开销。</p>
</section>
<section id="sec-design" class="level1">
<h1>GPU 核心微架构</h1>
<p>本节基于 <a href="#sec-researchmethodology" class="quarto-xref">小节&nbsp;3</a> 所述的方法，介绍我们对现代 NVIDIA 商用 GPU 核心微架构的发现。<a href="#fig-ourcore" class="quarto-xref">图&nbsp;3</a> 展示了 GPU 核心的关键组件。下文分别展开介绍发射调度器、前端、寄存器文件以及内存流水线。</p>
<div id="fig-ourcore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ourcore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/modern-nvidia-gpu/Rev_ourCore.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ourcore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;3: 现代 NVIDIA GPU 的 SM/Core 设计。
</figcaption>
</figure>
</div>
<section id="sec-warpscheduler" class="level2">
<h2 class="anchored" data-anchor-id="sec-warpscheduler">发射调度器</h2>
<p>本小节解析现代 NVIDIA GPU 的发射调度器。我们先在 <a href="#sec-readinesschecking" class="quarto-xref">小节&nbsp;5.1.1</a> 中描述每周期哪些 warp 会被视为“可发射”，再在 <a href="#sec-schedulingpolicy" class="quarto-xref">小节&nbsp;5.1.2</a> 中说明选择策略。</p>
<div id="fig-issue-scheduling-timeline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-issue-scheduling-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/modern-nvidia-gpu/Rev_issueTimeline.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-issue-scheduling-timeline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;4: 四个 warp 发射时间线示例。
</figcaption>
</figure>
</div>
<section id="sec-readinesschecking" class="level3">
<h3 class="anchored" data-anchor-id="sec-readinesschecking">Warp 就绪条件</h3>
<p>若一个 warp 在某周期要被视为其最老指令的候选发射者，需要满足若干条件。这些条件既依赖该 warp 的历史指令状态，也依赖核心的全局状态。</p>
<p>显然，需要指令缓冲区中存在有效指令。另一个条件是该 warp 的最老指令不能与同一 warp 中尚未完成的更老指令存在数据依赖。依赖由控制位进行软件处理，如 <a href="#sec-moderngpuarch" class="quarto-xref">小节&nbsp;4</a> 所述。</p>
<p>此外，对于固定延迟指令，只有在能够保证其发射后执行所需资源可用时，该 warp 才能在该周期发射最老指令。</p>
<p>其中一类资源是执行单元。执行单元存在输入锁存器，指令到达执行阶段时该锁存器必须为空。当执行单元宽度为半个 warp 时，锁存器会被占用两个周期；宽度为一个 warp 时则占用一个周期。</p>
<p>对于源操作数位于常量缓存（Constant Cache）的指令，标签查找在发射阶段进行。若所选 warp 的最老指令需要常量缓存而发生 miss，则调度器不会发射任何指令直到 miss 被服务；如果 4 个周期后 miss 仍未完成，则调度器切换到另一条指令就绪的 warp（选择最年轻的）。</p>
<p>关于寄存器文件读端口的可用性，我们观察到发射调度器并不会考虑“未来若干周期是否会发生端口冲突”。我们的实验表明，即使移除最后一个 <code>FFMA</code> 与 <code>CLOCK</code> 之间的 <code>NOP</code>，寄存器读冲突也不会阻止第二个 <code>CLOCK</code> 的发射。我们进行了大量实验以推断从发射到执行之间的流水线结构，虽然无法完全拟合所有案例，但以下模型对绝大多数实验有效，因此采用该模型：固定延迟指令在发射阶段与读操作数阶段之间有两个中间阶段。第一个阶段称为 Control，适用于固定和可变延迟指令，用于递增依赖计数器或读取时钟计数器等。由此可以解释：如果一条指令递增依赖计数器，紧随其后的指令又需要等待该计数器归零，则两者之间至少需要插入一个周期，否则递增在下一周期才生效，因此连续指令无法依赖计数器直接避免冒险，除非前一条指令设置了 Yield 或设置了大于 1 的停顿计数器。</p>
<p>第二个阶段仅用于固定延迟指令，我们称之为 Allocate。在该阶段检查寄存器文件读端口是否可用，若无法保证在后续周期无冲突读取操作数，则在该阶段停顿，直到可以保证读取。寄存器文件读写流水线及其缓存细节见 <a href="#sec-regfile" class="quarto-xref">小节&nbsp;5.3</a>。</p>
<p>可变延迟指令（如内存指令）在通过 Control 阶段后直接进入队列，不经过 Allocate。队列中的指令只有在确认不会发生读端口冲突时才进入寄存器文件读流水线。固定延迟指令优先于可变延迟指令获得读端口分配，因为固定延迟指令必须在固定周期内完成以保证依赖正确性。</p>
</section>
<section id="sec-schedulingpolicy" class="level3">
<h3 class="anchored" data-anchor-id="sec-schedulingpolicy">调度策略</h3>
<p>为揭示发射调度策略，我们设计了多种涉及多个 warp 的测试，记录每周期调度器选择哪个 warp 发射。该信息通过保存 GPU <code>CLOCK</code> 计数器的指令获取，但硬件不允许连续发射两条此类指令，因此我们在中间插入固定数量的其他指令（通常为 <code>NOP</code>），并变化 <code>Yield</code> 与停顿计数器控制位的取值。</p>
<p>实验结果表明，warp 调度器采用贪心策略：若同一 warp 满足就绪条件，则继续从该 warp 发射；当需要切换 warp 时，选择满足就绪条件的“最年轻”warp。</p>
<p><a href="#fig-issue-scheduling-timeline" class="quarto-xref">图&nbsp;4</a> 展示了四个 warp 在同一 sub-core 中执行时的发射时间线。每个 warp 执行相同的代码，包含 32 条彼此独立的指令，理论上每周期可发射 1 条。</p>
<p>在情况 (a) 中，所有停顿计数器、依赖掩码与 Yield 均为 0。调度器从最年轻的 warp（W3）开始发射，直到其 ICache miss；此时 W3 没有有效指令，调度器切换到 W2。由于 W2 复用了 W3 带入的指令，因此其 ICache 命中；当 W2 执行到 W3 miss 的位置时，miss 已被服务，后续指令命中，于是调度器继续贪心地完成 W2。随后调度器继续从 W3（最年轻）发射至结束，再转到 W1、W0。</p>
<p>情况 (b) 中，每个 warp 的第二条指令将停顿计数器设为 4。调度器在 W3 发射两条后切换至 W2，再两条后切换至 W1，然后回到 W3（其停顿计数器已归零）。当 W3、W2、W1 结束后，调度器开始发射 W0。W0 发射第二条指令后，由于没有其他 warp 可隐藏停顿，产生 4 个气泡。</p>
<p>情况 (c) 中，每个 warp 的第二条指令设置 Yield。调度器在发射第二条指令后切换到其他 warp 中最年轻的一个，例如 W3 切换到 W2，W2 再切回 W3。我们还测试了“Yield 置位且无其他 warp 可选”的情况（图中未示），此时调度器产生 1 个周期的气泡。</p>
<p>我们将该策略称为“编译器引导的贪心后选最年轻（CGGTY）”，因为调度器由控制位（停顿计数器、Yield 与依赖计数器）引导。</p>
<p>需要说明的是，我们仅验证了同一 CTA 内 warp 的行为；尚未有可靠方法分析不同 CTA 之间 warp 的交互。</p>
</section>
</section>
<section id="sec-frontend" class="level2">
<h2 class="anchored" data-anchor-id="sec-frontend">前端</h2>
<p>根据 NVIDIA 多份文档中的 SM 结构图<span class="citation" data-cites="voltaPaper turingPaper amperePaper hopperPaper adaPaper voltaHotChips turingHotChips"><a href="#ref-voltaPaper" role="doc-biblioref">[19]</a>, <a href="#ref-turingPaper" role="doc-biblioref">[20]</a>, <a href="#ref-amperePaper" role="doc-biblioref">[21]</a>, <a href="#ref-hopperPaper" role="doc-biblioref">[22]</a>, <a href="#ref-adaPaper" role="doc-biblioref">[23]</a>, <a href="#ref-voltaHotChips" role="doc-biblioref">[24]</a>, <a href="#ref-turingHotChips" role="doc-biblioref">[25]</a></span>，SM 包含四个 sub-core，warp 以轮转方式分配到 sub-core（即 warp ID <code>mod 4</code>）<span class="citation" data-cites="dissectingVolta dissectingTuring"><a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>。每个 sub-core 有私有 L0 指令缓存，并连接到全 SM 共享的 L1 指令缓存。我们假设存在仲裁器协调多个 sub-core 的请求。</p>
<p>每个 L0 ICache 都有指令预取器<span class="citation" data-cites="nvidiaInstPrefeching"><a href="#ref-nvidiaInstPrefeching" role="doc-biblioref">[44]</a></span>。我们的实验印证了 Cao 等人关于 GPU 指令预取有效性的结论<span class="citation" data-cites="GPUinstPrefeching"><a href="#ref-GPUinstPrefeching" role="doc-biblioref">[45]</a></span>。尽管我们无法确认 NVIDIA 的具体实现，但推测为类似流缓冲的简单方案<span class="citation" data-cites="streamBufferPrefetching"><a href="#ref-streamBufferPrefetching" role="doc-biblioref">[46]</a></span>，即在 miss 发生时预取后续连续的缓存行。基于分析，我们假设流缓冲大小为 16（见 <a href="#sec-results-instruction-prefetching" class="quarto-xref">小节&nbsp;7.3</a>）。</p>
<p>我们无法通过实验确认精确的取指策略，但若其与发射策略差异过大，将频繁出现“指令缓冲区无有效指令”的情况，而我们并未观察到这一现象。因此，我们假设每个 sub-core 每周期可取指并译码 1 条指令。取指调度器优先从上次（或最近一次）发射指令的 warp 取指，除非该 warp 的指令缓冲区中已存在的指令数加上在途取指数达到缓冲区容量。此时调度器切换到指令缓冲区有空位的最年轻 warp。我们假设每个 warp 有 3 个指令缓冲区条目，足以支撑“贪心发射”策略，因为从取指到发射有 2 个流水阶段。如果缓冲区仅有 2 项，贪心策略将被破坏：例如在所有请求 ICache 命中、所有 warp 缓冲区均满的情况下，若第 1 周期发射 W1 同时取指 W0，第 2 周期将发射 W1 的第 2 条并取指第 3 条；第 3 周期 W1 的第 3 条仍在译码中，缓冲区无有效指令，贪心策略失败，被迫切换 warp。3 项缓冲区可避免该问题，这与我们的实验一致。多数文献假设取指/译码宽度为 2 且缓冲区为 2 项，并且只有当缓冲区为空才取指，这会导致每两个连续指令后就切换 warp，与我们的观察不符。</p>
</section>
<section id="sec-regfile" class="level2">
<h2 class="anchored" data-anchor-id="sec-regfile">寄存器文件</h2>
<p>我们通过大量实验（不同 SASS 指令组合、不同寄存器文件端口压力、是否使用寄存器文件缓存）来揭示寄存器文件组织。</p>
<p>现代 NVIDIA GPU 具有多种寄存器文件：</p>
<ul>
<li><strong>常规寄存器（Regular）</strong>：最近架构每个 SM 有 65536 个 32 位寄存器<span class="citation" data-cites="voltaPaper turingPaper amperePaper hopperPaper adaPaper"><a href="#ref-voltaPaper" role="doc-biblioref">[19]</a>, <a href="#ref-turingPaper" role="doc-biblioref">[20]</a>, <a href="#ref-amperePaper" role="doc-biblioref">[21]</a>, <a href="#ref-hopperPaper" role="doc-biblioref">[22]</a>, <a href="#ref-adaPaper" role="doc-biblioref">[23]</a></span>，用于保存线程计算值。寄存器按 32 个为一组，对应 warp 中 32 个线程，形成 2048 个“warp 寄存器”。寄存器在 sub-core 间均匀分布，每个 sub-core 的寄存器文件分成两个 bank<span class="citation" data-cites="dissectingVolta dissectingTuring"><a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>。每个 warp 可使用 1 至 256 个寄存器，编译时确定。每 warp 使用寄存器越多，SM 并行 warp 数越少。</li>
<li><strong>统一寄存器（Uniform）</strong>：每个 warp 有 64 个私有 32 位寄存器，用于保存该 warp 所有线程共享的值<span class="citation" data-cites="dissectingTuring"><a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>。</li>
<li><strong>谓词寄存器（Predicate）</strong>：每个 warp 有 8 个 32 位寄存器，每个 bit 对应 warp 中一个线程，用于指示是否执行指令及分支走向。</li>
<li><strong>统一谓词寄存器（Uniform Predicate）</strong>：每个 warp 有 8 个 1-bit 寄存器，用于全 warp 共享的谓词。</li>
<li><strong>SB 寄存器</strong>：每个 warp 有 6 个“依赖计数器”寄存器，用于追踪可变延迟依赖（见 <a href="#sec-moderngpuarch" class="quarto-xref">小节&nbsp;4</a>）。</li>
<li><strong>B 寄存器</strong>：每个 warp 至少有 16 个 <code>B</code> 寄存器用于控制流重汇合（re-convergence）<span class="citation" data-cites="mojtabaControlFlow"><a href="#ref-mojtabaControlFlow" role="doc-biblioref">[47]</a></span>。</li>
<li><strong>特殊寄存器</strong>：用于存放线程 ID、block ID 等特殊值。</li>
</ul>
<p>与以往假设存在 operand collector 以处理寄存器端口冲突的工作不同<span class="citation" data-cites="GPU2OcusSubcore accelsim gpgpuBook"><a href="#ref-accelsim" role="doc-biblioref">[13]</a>, <a href="#ref-gpgpuBook" role="doc-biblioref">[15]</a>, <a href="#ref-GPU2OcusSubcore" role="doc-biblioref">[48]</a></span>，现代 NVIDIA GPU 并未使用 operand collector。若使用 collector，会引入发射到写回的可变延迟，使得 NVIDIA ISA 的固定延迟无法在编译期确定，无法正确依赖管理（见 <a href="#sec-moderngpuarch" class="quarto-xref">小节&nbsp;4</a>）。我们通过多组生产者—消费者指令序列的实验验证了 collector 的不存在：无论寄存器端口冲突数量如何，停顿计数器所需值与指令执行时间均保持不变。</p>
<p>实验显示，每个寄存器文件 bank 有一个 1024-bit 专用写端口。此外，当一条 load 指令与一条固定延迟指令在同周期完成时，被延迟的是 load 指令；而当两个固定延迟指令（如 <code>IADD3</code> 与 <code>IMAD</code>）写同一 bank 时，两者都不延迟。这表明固定延迟指令使用了类似 Fermi 中引入的结果队列<span class="citation" data-cites="fermiWhitePaper"><a href="#ref-fermiWhitePaper" role="doc-biblioref">[49]</a></span>。其消费者不被延迟，说明存在旁路（bypass）以在写回前转发结果。</p>
<p>在读方面，我们观察到每 bank 1024-bit 带宽。通过连续 <code>FADD</code>、<code>FMUL</code>、<code>FFMA</code> 指令测得这一结果。<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>例如，当 <code>FMUL</code> 的两个源操作数来自同一 bank 时会产生 1 个周期气泡；若来自不同 bank 则无气泡。<code>FFMA</code> 的三个源操作数都在同一 bank 时会产生 2 个周期气泡。</p>
<p>我们未能找到一个完全匹配所有案例的读端口仲裁策略，因为气泡生成还依赖指令类型与操作数角色。最接近实验结果的模型为：固定延迟指令在发射与读操作数之间有两个中间阶段 Control 与 Allocate（见 <a href="#sec-readinesschecking" class="quarto-xref">小节&nbsp;5.1.1</a>）。Allocate 负责保留寄存器文件读端口；每 bank 有一个 1024-bit 读端口，并通过寄存器文件缓存缓解读冲突。实验显示所有固定延迟指令读取操作数会持续 3 个周期，即便某些周期空闲（例如仅有两个源操作数），因为 <code>FADD</code> 与 <code>FMUL</code> 的延迟与 <code>FFMA</code> 相同，而 <code>FFMA</code> 不论三操作数是否在同一 bank 延迟都相同。若指令在 Allocate 阶段发现无法在后续三周期内读取完所有操作数，则其被阻塞在该阶段并向上游施加气泡，直到能够预留所需端口。</p>
<section id="sec-reg-file-cache" class="level3">
<h3 class="anchored" data-anchor-id="sec-reg-file-cache">寄存器文件缓存</h3>
<p>寄存器文件缓存（RFC）可缓解寄存器文件端口争用并节能，这一思路已被多项研究探讨<span class="citation" data-cites="registerFileCacheFirst registerFileCacheSimilar BOW ltrf mojtabaIsca"><a href="#ref-registerFileCacheFirst" role="doc-biblioref">[50]</a>, <a href="#ref-registerFileCacheSimilar" role="doc-biblioref">[51]</a>, <a href="#ref-BOW" role="doc-biblioref">[52]</a>, <a href="#ref-ltrf" role="doc-biblioref">[53]</a>, <a href="#ref-mojtabaIsca" role="doc-biblioref">[54]</a></span>。</p>
<p>我们的实验表明 NVIDIA 的设计与 Gebhart 等人的方案类似<span class="citation" data-cites="registerFileCacheSimilar"><a href="#ref-registerFileCacheSimilar" role="doc-biblioref">[51]</a></span>。RFC 由编译器控制，仅用于常规寄存器操作数。关于 Last Result File 结构，我们称之为结果队列，其行为类似，但并未采用两级发射调度器（见 <a href="#sec-schedulingpolicy" class="quarto-xref">小节&nbsp;5.1.2</a>）。</p>
<p>RFC 组织结构如下：每个 sub-core 的两个寄存器 bank 各有一个入口，每个入口存放三个 1024-bit 值，对应三类常规寄存器源操作数。总容量为 6 个 1024-bit 操作数值（子条目）。某些指令的一个操作数可能需要连续两个寄存器（如张量核心指令），此时两个寄存器分别来自不同 bank，并缓存到对应入口。</p>
<p>编译器控制分配策略。当指令发射并读取操作数时，若该操作数设置了 <code>reuse</code>，其值将被写入 RFC。若后续指令来自同一 warp，且寄存器 ID 与 RFC 中一致、并且该操作数在指令中的位置一致，则可从 RFC 命中。若有新的读请求到达同一 bank 和同一操作数位置，则该缓存值将失效（无论命中与否）。这一行为在下面示例 2 中展示：为了让第三条指令命中 <code>R2</code>，第二条指令必须再次为 <code>R2</code> 设置 reuse，即便 <code>R2</code> 已经缓存。</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 寄存器文件缓存行为示例</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 1</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>IADD3 R1, R2.reuse, R3, R4 <span class="co"># Allocates R2</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>FFMA R5, R2, R7, R8 <span class="co"># R2 hits and becomes unavailable</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>IADD3 R10, R2, R12, R13 <span class="co"># R2 misses</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 2</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>IADD3 R1, R2.reuse, R3, R4 <span class="co"># Allocates R2</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>FFMA R5, R2.reuse, R7, R8 <span class="co"># R2 hits and is retained</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>IADD3 R10, R2, R12, R13 <span class="co"># R2 hits</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 3. R2 misses in the second instruction since it is</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># cached in another slot. R2 remains available in the first</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># slot since R7 uses a different bank</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>IADD3 R1, R2.reuse, R3, R4 <span class="co"># Allocates R2</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>FFMA R5, R7, R2, R8 <span class="co"># R2 misses</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>IADD3 R10, R2, R12, R13 <span class="co"># R2 hits</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 4. R2 misses in the third instruction since the</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># second instruction uses a different register that goes to</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># the same bank in the same operand slot</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>IADD3 R1, R2.reuse, R3, R4 <span class="co"># Allocates R2</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>FFMA R5, R4, R7, R8 <span class="co"># R4 misses and R2 becomes unavailable</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>IADD3 R10, R2, R12, R13 <span class="co"># R2 misses</span></span></code></pre></div><button title="复制到剪贴板" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="sec-memory-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="sec-memory-pipeline">内存流水线</h2>
<p>现代 NVIDIA GPU 的内存流水线包含每个 sub-core 本地的初始阶段，而实际访存的后续阶段由四个 sub-core 共享，因为数据缓存与共享内存为 SM 共享结构<span class="citation" data-cites="voltaHotChips turingHotChips"><a href="#ref-voltaHotChips" role="doc-biblioref">[24]</a>, <a href="#ref-turingHotChips" role="doc-biblioref">[25]</a></span>。本节揭示每个 sub-core 的 load/store 队列大小、sub-core 向共享结构发送请求的速率，以及不同内存指令的延迟。</p>
<p>注意内存访问分为两大类：共享内存访问（SM 内部、线程块共享）与全局内存访问（GPU 主存）。</p>
<p>为了确定队列大小与内存带宽，我们进行了一系列实验，每个 sub-core 要么执行一个 warp，要么空闲。每个 warp 执行一串相互独立的 load/store 指令，这些指令始终命中数据缓存或共享内存，并使用常规寄存器。<a href="#tbl-memoryconsecutive" class="quarto-xref">表&nbsp;1</a> 展示实验结果。第一列为指令序号，其余四列为不同活跃 sub-core 数量下该指令的发射周期（每格按周期升序列出所有活跃 sub-core）。</p>
<div id="tbl-memoryconsecutive" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-memoryconsecutive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;1: 每条内存指令的发射周期（每格为所有活跃 sub-core 按周期升序的列表）。
</figcaption>
<div aria-describedby="tbl-memoryconsecutive-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>指令编号</th>
<th>活跃 sub-core 数 = 1</th>
<th>活跃 sub-core 数 = 2</th>
<th>活跃 sub-core 数 = 3</th>
<th>活跃 sub-core 数 = 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>2/2</td>
<td>2/2/2</td>
<td>2/2/2/2</td>
</tr>
<tr class="even">
<td>2</td>
<td>3</td>
<td>3/3</td>
<td>3/3/3</td>
<td>3/3/3/3</td>
</tr>
<tr class="odd">
<td>3</td>
<td>4</td>
<td>4/4</td>
<td>4/4/4</td>
<td>4/4/4/4</td>
</tr>
<tr class="even">
<td>4</td>
<td>5</td>
<td>5/5</td>
<td>5/5/5</td>
<td>5/5/5/5</td>
</tr>
<tr class="odd">
<td>5</td>
<td>6</td>
<td>6/6</td>
<td>6/6/6</td>
<td>6/6/6/6</td>
</tr>
<tr class="even">
<td>6</td>
<td>13</td>
<td>13/15</td>
<td>13/15/17</td>
<td>13/15/17/19</td>
</tr>
<tr class="odd">
<td>7</td>
<td>17</td>
<td>17/19</td>
<td>19/21/23</td>
<td>21/23/25/27</td>
</tr>
<tr class="even">
<td>8</td>
<td>21</td>
<td>21/23</td>
<td>25/27/29</td>
<td>29/31/33/35</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(i&gt;8\)</span></td>
<td><span class="math inline">\((i-1)+4\)</span></td>
<td><span class="math inline">\((i-1)+4\)</span></td>
<td><span class="math inline">\((i-1)+6\)</span></td>
<td><span class="math inline">\((i-1)+8\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>可以看到，在 Ampere 中每个 sub-core 可连续 5 条内存指令按每周期一条发射，第 6 条指令的发射会产生停顿，且停顿周期取决于活跃 sub-core 数量。这表明每个 sub-core 可无阻塞地缓冲 5 条指令，而全局共享结构可每两周期从任一 sub-core 接收一个内存请求。观察多 sub-core 情形可知：第 6 条及之后的指令在每个 sub-core 上以两周期间隔发射。</p>
<p>我们还可推断 sub-core 中的地址计算吞吐率为每 4 周期一条指令：当只有一个 sub-core 活跃时，第 6 条指令之后出现 4 周期间隔。两 sub-core 活跃时，由于共享结构吞吐率为每 2 周期一条，故每个 sub-core 可每 4 周期发射一条；更多 sub-core 活跃时共享结构成为瓶颈。例如四 sub-core 活跃时，每个 sub-core 只能每 8 周期发射一条，因为共享结构最大吞吐为每 2 周期一条。</p>
<p>关于每个 sub-core 内存队列大小，我们估计为 4，尽管每个 sub-core 可缓冲 5 条连续指令。指令进入单元时占用槽位，离开单元时释放槽位。</p>
<p>我们测量了不同内存指令在缓存命中且单线程执行时的两类延迟。第一类是从 load 发射到消费者或覆盖同一目的寄存器的指令可以发射的最早时间（RAW/WAW 延迟；store 不产生寄存器 RAW/WAW）。第二类是从 load/store 发射到能够写入其源寄存器的指令可发射的最早时间（WAR 延迟）。结果见 <a href="#tbl-mem-latencies" class="quarto-xref">表&nbsp;2</a>。</p>
<div id="tbl-mem-latencies" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mem-latencies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;2: 内存指令延迟（周期）。带 <code>*</code> 的值为近似值。
</figcaption>
<div aria-describedby="tbl-mem-latencies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>指令</th>
<th>地址寄存器类型</th>
<th style="text-align: right;">WAR</th>
<th style="text-align: right;">RAW/WAW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Load Global 32 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="even">
<td>Load Global 64 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="odd">
<td>Load Global 128 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">35</td>
</tr>
<tr class="even">
<td>Load Global 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="odd">
<td>Load Global 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="even">
<td>Load Global 128 bit</td>
<td>Regular</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">38</td>
</tr>
<tr class="odd">
<td>Store Global 32 bit</td>
<td>Uniform</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Global 64 bit</td>
<td>Uniform</td>
<td style="text-align: right;">12*</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Store Global 128 bit</td>
<td>Uniform</td>
<td style="text-align: right;">16*</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Global 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Store Global 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Global 128 bit</td>
<td>Regular</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Load Shared 32 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="even">
<td>Load Shared 64 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd">
<td>Load Shared 128 bit</td>
<td>Uniform</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td>Load Shared 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td>Load Shared 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td>Load Shared 128 bit</td>
<td>Regular</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td>Store Shared 32 bit</td>
<td>Uniform</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Shared 64 bit</td>
<td>Uniform</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Store Shared 128 bit</td>
<td>Uniform</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Shared 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Store Shared 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="even">
<td>Store Shared 128 bit</td>
<td>Regular</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>Load Constant 32 bit</td>
<td>Immediate</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td>Load Constant 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="odd">
<td>Load Constant 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="even">
<td><code>LDGSTS</code> 32 bit</td>
<td>Regular</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td><code>LDGSTS</code> 64 bit</td>
<td>Regular</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="even">
<td><code>LDGSTS</code> 128 bit</td>
<td>Regular</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">39</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>我们观察到：使用统一寄存器计算地址的全局内存访问比使用常规寄存器更快，因为前者所有线程共享同一地址，仅需计算一个地址，而后者每线程可能不同。</p>
<p>共享内存 load 的延迟低于全局内存。其 WAR 延迟对常规与统一寄存器相同，而 RAW/WAW 延迟在统一寄存器时少 1 个周期。这表明共享内存的地址计算在共享结构中完成，WAR 依赖在源寄存器读取后即可解除。</p>
<p>如预期，延迟也受访问粒度影响。对于 WAR 依赖，load 延迟不随数据大小变化，因为源操作数仅用于地址计算且大小固定；对于 store，写入数据也是源操作数，数据越大 WAR 延迟越高。RAW/WAW 依赖（仅适用于 load）随数据大小增大而增大，因为需要更多数据传输到寄存器文件。我们测得该传输带宽为每周期 512 bit。</p>
<p>此外，常量缓存的 WAR 延迟显著高于全局内存 load，而 RAW/WAW 延迟略低。我们尚无法给出合理解释。但我们发现，固定延迟指令访问常量空间使用不同的缓存层级：通过 <code>LDC</code> 预加载常量地址并等待完成后，再发射使用同一常量地址的固定延迟指令，会出现约 79 周期的 miss 延迟，而非命中。这表明固定延迟指令访问常量空间使用 L0 FL（固定延迟）常量缓存，而 <code>LDC</code> 指令使用 L0 VL（可变延迟）常量缓存。</p>
<p>最后，我们分析 <code>LDGSTS</code> 指令，该指令用于减少寄存器文件压力并提升数据传输效率<span class="citation" data-cites="patentLDGSTS"><a href="#ref-patentLDGSTS" role="doc-biblioref">[55]</a></span>。它从全局内存加载数据并直接写入共享内存，绕过寄存器文件，节省指令与寄存器。其延迟与指令粒度无关。WAR 依赖在地址计算完成后解除；RAW/WAW 依赖在读阶段完成后解除。</p>
</section>
</section>
<section id="sec-modeling" class="level1">
<h1>建模</h1>
<p>我们重新设计 Accel-Sim 框架的 SM/core 模型<span class="citation" data-cites="accelsim"><a href="#ref-accelsim" role="doc-biblioref">[13]</a></span>，通过修改流水线实现 <a href="#sec-moderngpuarch" class="quarto-xref">小节&nbsp;4</a> 与 <a href="#sec-design" class="quarto-xref">小节&nbsp;5</a> 解释的所有细节（见 <a href="#fig-ourcore" class="quarto-xref">图&nbsp;3</a>）。主要新增组件如下：</p>
<p>首先，我们为每个 sub-core 添加了 L0 指令缓存与流缓冲预取器。L0 指令与常量缓存通过可参数化延迟连接到 L1 指令/常量缓存。缓存容量、层级与延迟依据既有测量与 Jia 等人关于 Ampere 的研究确定<span class="citation" data-cites="dissectingAmpere"><a href="#ref-dissectingAmpere" role="doc-biblioref">[56]</a></span>。</p>
<p>我们修改了发射阶段以支持控制位、固定延迟指令对新 L0 常量缓存的标签查询，以及新的 CGGTY 发射调度器。我们加入了 Control 阶段（递增依赖计数器）与 Allocate 阶段（固定延迟指令检查寄存器文件与 RFC 冲突）。</p>
<p>针对内存指令，我们为每个 sub-core 建模了新的本地单元，并为 sub-core 共享部分建模了共享单元，其延迟与上一节一致。</p>
<p>此外，Abdelkhalik 等人表明张量核心指令延迟依赖其操作数数值类型与尺寸<span class="citation" data-cites="demystifyingAmpere"><a href="#ref-demystifyingAmpere" role="doc-biblioref">[57]</a></span>，因此我们在模型中为不同操作数类型与尺寸设置了对应延迟。</p>
<p>我们还建模了以下细节：在缺乏每 sub-core 双精度执行单元的架构中，双精度指令使用全 sub-core 共享的执行流水线；对使用多个寄存器的操作数，精确建模读写时序（此前模型常将其简化为一个寄存器）；修正此前工作中指令地址报告的部分不准确之处<span class="citation" data-cites="cams2023paper"><a href="#ref-cams2023paper" role="doc-biblioref">[58]</a></span>。</p>
<p>除模拟器的 SM/core 模型更新外，我们还扩展了 tracer 工具：导出所有操作数类型的 ID（常规、统一、谓词、立即数等）；并增加获取控制位的能力（NVBit 不提供），通过 CUDA 二进制工具<span class="citation" data-cites="cudaBinaryUtils"><a href="#ref-cudaBinaryUtils" role="doc-biblioref">[59]</a></span>在编译时提取 SASS。为此，我们修改应用编译流程，使其在编译期生成与微架构相关的代码而非 JIT。遗憾的是，少数内核（均来自 Deepbench）无法获取 SASS，导致控制位无法提取。对此我们采用“混合依赖模式”：无法获取控制位的内核使用传统记分牌，其他内核使用控制位。</p>
<p>我们还扩展工具以捕获通过描述符访问常量缓存或全局内存的指令。尽管该访问方式被认为在 Hopper 才引入<span class="citation" data-cites="cudaBinaryUtils"><a href="#ref-cudaBinaryUtils" role="doc-biblioref">[59]</a></span>，我们发现 Ampere 已使用。描述符是编码内存访问的新方式，包含两个操作数：第一个为统一寄存器，用于编码指令语义；第二个编码地址。我们扩展 tracer 捕获地址，但未能追踪统一寄存器中编码的语义。</p>
<p>我们计划公开 Accel-Sim 框架中的所有模拟器与 tracer 改动。</p>
</section>
<section id="sec-validation" class="level1">
<h1>验证</h1>
<p>本节评估所提出 GPU 核心微架构的准确性。首先在 <a href="#sec-methodoloy" class="quarto-xref">小节&nbsp;7.1</a> 描述方法；随后在 <a href="#sec-cycle-accuracy" class="quarto-xref">小节&nbsp;7.2</a> 验证设计；在 <a href="#sec-eval-rf" class="quarto-xref">小节&nbsp;7.4</a> 中研究寄存器文件缓存与读端口数量的影响；在 <a href="#sec-results-instruction-prefetching" class="quarto-xref">小节&nbsp;7.3</a> 中分析指令预取器，在 <a href="#sec-deps-analysis" class="quarto-xref">小节&nbsp;7.5</a> 中分析依赖检查机制；最后在 <a href="#sec-use-other-archs" class="quarto-xref">小节&nbsp;7.6</a> 讨论模型向其他 NVIDIA 架构的迁移。</p>
<section id="sec-methodoloy" class="level2">
<h2 class="anchored" data-anchor-id="sec-methodoloy">方法</h2>
<p>我们通过将模拟器结果与真实 GPU 的硬件计数器指标进行对比来验证准确性。使用了四种 Ampere GPU<span class="citation" data-cites="amperePaper"><a href="#ref-amperePaper" role="doc-biblioref">[21]</a></span>（规格见 <a href="#tbl-gpus-specs-and-results" class="quarto-xref">表&nbsp;4</a>），CUDA 版本为 11.4，NVBit 为 1.5.5。我们也将模型与原始 Accel-Sim 进行对比，因为新模型基于其构建。</p>
<p>我们选取了来自 12 个基准套件的广泛基准。各套件、应用数量与输入集数量见 <a href="#tbl-bench-suites" class="quarto-xref">表&nbsp;3</a>。总计 143 个基准，其中 83 个为不同应用，其余为同应用不同输入。</p>
<div id="tbl-bench-suites" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bench-suites-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;3: 基准套件。
</figcaption>
<div aria-describedby="tbl-bench-suites-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>套件</th>
<th style="text-align: right;">应用数</th>
<th style="text-align: right;">输入集</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cutlass<span class="citation" data-cites="cutlass"><a href="#ref-cutlass" role="doc-biblioref">[60]</a></span></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td>Deepbench<span class="citation" data-cites="deepbenchWeb"><a href="#ref-deepbenchWeb" role="doc-biblioref">[61]</a></span></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">27</td>
</tr>
<tr class="odd">
<td>Dragon<span class="citation" data-cites="dragon"><a href="#ref-dragon" role="doc-biblioref">[62]</a></span></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td>GPU Microbenchmark<span class="citation" data-cites="accelsim"><a href="#ref-accelsim" role="doc-biblioref">[13]</a></span></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td>ISPASS 2009<span class="citation" data-cites="gpgpusim3"><a href="#ref-gpgpusim3" role="doc-biblioref">[12]</a></span></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>Lonestargpu<span class="citation" data-cites="lonestar"><a href="#ref-lonestar" role="doc-biblioref">[63]</a></span></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Pannotia<span class="citation" data-cites="pannotia"><a href="#ref-pannotia" role="doc-biblioref">[64]</a></span></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="even">
<td>Parboil<span class="citation" data-cites="parboil"><a href="#ref-parboil" role="doc-biblioref">[65]</a></span></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Polybench<span class="citation" data-cites="polybench"><a href="#ref-polybench" role="doc-biblioref">[66]</a></span></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>Proxy Apps DOE<span class="citation" data-cites="proxy"><a href="#ref-proxy" role="doc-biblioref">[67]</a></span></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td>Rodinia 2<span class="citation" data-cites="rodinia"><a href="#ref-rodinia" role="doc-biblioref">[68]</a></span></td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td>Rodinia 3<span class="citation" data-cites="rodinia"><a href="#ref-rodinia" role="doc-biblioref">[68]</a></span></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="odd">
<td><strong>合计</strong></td>
<td style="text-align: right;"><strong>83</strong></td>
<td style="text-align: right;"><strong>143</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="sec-cycle-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="sec-cycle-accuracy">性能准确性</h2>
<div id="tbl-gpus-specs-and-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-gpus-specs-and-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;4: GPU 规格与性能准确性。
</figcaption>
<div aria-describedby="tbl-gpus-specs-and-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">RTX 3080</th>
<th style="text-align: right;">RTX 3080 Ti</th>
<th style="text-align: right;">RTX 3090</th>
<th style="text-align: right;">RTX A6000</th>
<th style="text-align: right;">RTX 2080 Ti</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>规格</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>核心频率</td>
<td style="text-align: right;">1710 MHz</td>
<td style="text-align: right;">1365 MHz</td>
<td style="text-align: right;">1395 MHz</td>
<td style="text-align: right;">1800 MHz</td>
<td style="text-align: right;">1350 MHz</td>
</tr>
<tr class="odd">
<td>显存频率</td>
<td style="text-align: right;">9500 MHz</td>
<td style="text-align: right;">9500 MHz</td>
<td style="text-align: right;">9750 MHz</td>
<td style="text-align: right;">8000 MHz</td>
<td style="text-align: right;">7000 MHz</td>
</tr>
<tr class="even">
<td>SM 数量</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="odd">
<td>每 SM warp 数</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td>每 SM 共享内存/L1D</td>
<td style="text-align: right;">128 KB</td>
<td style="text-align: right;">128 KB</td>
<td style="text-align: right;">128 KB</td>
<td style="text-align: right;">128 KB</td>
<td style="text-align: right;">96 KB</td>
</tr>
<tr class="odd">
<td>内存分区数</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td>L2 总容量</td>
<td style="text-align: right;">5 MB</td>
<td style="text-align: right;">6 MB</td>
<td style="text-align: right;">6 MB</td>
<td style="text-align: right;">6 MB</td>
<td style="text-align: right;">5.5 MB</td>
</tr>
<tr class="odd">
<td><strong>验证</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td>我们模型 MAPE</td>
<td style="text-align: right;">17.15%</td>
<td style="text-align: right;">18%</td>
<td style="text-align: right;">17.93%</td>
<td style="text-align: right;">13.98%</td>
<td style="text-align: right;">19.73%</td>
</tr>
<tr class="odd">
<td>Accel-Sim MAPE</td>
<td style="text-align: right;">27.95%</td>
<td style="text-align: right;">28.19%</td>
<td style="text-align: right;">28.5%</td>
<td style="text-align: right;">32.22%</td>
<td style="text-align: right;">26.67%</td>
</tr>
<tr class="even">
<td>我们模型相关系数</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.98</td>
</tr>
<tr class="odd">
<td>Accel-Sim 相关系数</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.95</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-gpus-specs-and-results" class="quarto-xref">表&nbsp;4</a> 展示了我们模型与 Accel-Sim 相对于真实硬件的 MAPE。可以看到，我们模型在所有 GPU 上都更准确，且对最大规模的 NVIDIA RTX A6000，MAPE 不到 Accel-Sim 的一半。相关系数方面，两者接近，但我们略优。</p>
<div id="fig-cycles-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cycles-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../assets/modern-nvidia-gpu/AbsError_Cycles_general.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cycles-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
图&nbsp;5: NVIDIA RTX A6000 在各基准下的绝对百分比误差。基准按误差从小到大排序。
</figcaption>
</figure>
</div>
<p><a href="#fig-cycles-results" class="quarto-xref">图&nbsp;5</a> 展示了 RTX A6000 上两种模型的 APE 分布（基准按误差排序）。我们模型在所有应用上 APE 更低，并且对约半数应用差距显著。Accel-Sim 在 10 个应用上 APE 大于等于 100%，最坏达到 543%，而我们的模型 APE 从未超过 62%。以 90 分位为衡量尾部准确性，Accel-Sim 为 82.64%，而我们为 31.47%。这表明我们的模型明显更准确且更稳健。</p>
</section>
<section id="sec-results-instruction-prefetching" class="level2">
<h2 class="anchored" data-anchor-id="sec-results-instruction-prefetching">指令预取的敏感性分析</h2>
<p>流缓冲指令预取器的参数对模型准确性影响很大。我们评估了多种配置：关闭预取、完美指令缓存，以及流缓冲大小为 1、2、4、8、16、32 的配置，均基于 RTX A6000。结果见 <a href="#tbl-prefetching-analysis" class="quarto-xref">表&nbsp;5</a>，可见最佳准确性对应流缓冲大小为 16。</p>
<div id="tbl-prefetching-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prefetching-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;5: 不同预取配置的 MAPE 与相对性能提升。
</figcaption>
<div aria-describedby="tbl-prefetching-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>配置</th>
<th style="text-align: right;">关闭</th>
<th style="text-align: right;">1</th>
<th style="text-align: right;">2</th>
<th style="text-align: right;">4</th>
<th style="text-align: right;">8</th>
<th style="text-align: right;">16</th>
<th style="text-align: right;">32</th>
<th style="text-align: right;">完美 ICache</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAPE</td>
<td style="text-align: right;">56.61%</td>
<td style="text-align: right;">43.94%</td>
<td style="text-align: right;">28.59%</td>
<td style="text-align: right;">18.55%</td>
<td style="text-align: right;">14.67%</td>
<td style="text-align: right;">13.98%</td>
<td style="text-align: right;">14.35%</td>
<td style="text-align: right;">15.2%</td>
</tr>
<tr class="even">
<td>加速比</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.08x</td>
<td style="text-align: right;">1.2x</td>
<td style="text-align: right;">1.33x</td>
<td style="text-align: right;">1.42x</td>
<td style="text-align: right;">1.47x</td>
<td style="text-align: right;">1.46x</td>
<td style="text-align: right;">1.58x</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>从 <a href="#tbl-prefetching-analysis" class="quarto-xref">表&nbsp;5</a> 的加速结果还可得出一条结论：简单的流缓冲预取器在 GPU 上的行为接近完美指令缓存。这是因为 sub-core 中的不同 warp 往往执行同一代码区域，而典型 GPGPU 应用控制流较简单，预取连续 <span class="math inline">\(N\)</span> 行通常有效。由于 GPU 不进行分支预测，采用 Fetch-Directed 预取<span class="citation" data-cites="fdpPrefetching"><a href="#ref-fdpPrefetching" role="doc-biblioref">[69]</a></span> 不划算。</p>
<p>就仿真准确性而言，当不研究指令缓存增强时，完美指令缓存通常能以更高速度提供近似准确性。但对控制流较复杂的基准（如 Rodinia 的 <code>dwt2d</code>、<code>lud</code>、<code>nw</code>），完美指令缓存或不使用流缓冲会导致显著不准确（相对完美 ICache 误差超过 20%，相对无预取甚至超过 200%）。这是因为完美 ICache 无法体现频繁跳转带来的性能惩罚，而无预取则过度惩罚程序的其他部分，这也表明这些基准仍有改进空间。</p>
</section>
<section id="sec-eval-rf" class="level2">
<h2 class="anchored" data-anchor-id="sec-eval-rf">寄存器文件架构的敏感性分析</h2>
<p><a href="#tbl-rf-analysis" class="quarto-xref">表&nbsp;6</a> 展示了寄存器文件缓存（RFC）与每 bank 读端口数量对准确性与性能的影响，并给出了理想配置（所有操作数可在一个周期取回）。总体平均性能与准确性在各配置间相近，但特定基准表现更微妙：例如计算密集型的 <code>MaxFlops</code>（Accel-Sim GPU Microbenchmark）与使用 <code>sgemm</code> 参数的 Cutlass<span class="citation" data-cites="accelsim cutlass"><a href="#ref-accelsim" role="doc-biblioref">[13]</a>, <a href="#ref-cutlass" role="doc-biblioref">[60]</a></span>。这两者高度依赖固定延迟算术指令，而这类指令通常有 3 个操作数，易受寄存器文件访问限制影响。</p>
<div id="tbl-rf-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rf-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;6: 不同寄存器文件配置的 MAPE 与相对性能。
</figcaption>
<div aria-describedby="tbl-rf-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>配置</th>
<th style="text-align: right;">1R + RFC 开</th>
<th style="text-align: right;">1R + RFC 关</th>
<th style="text-align: right;">2R + RFC 关</th>
<th style="text-align: right;">理想</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MAPE</td>
<td style="text-align: right;">13.98%</td>
<td style="text-align: right;">16.05%</td>
<td style="text-align: right;">13.38%</td>
<td style="text-align: right;">13.57%</td>
</tr>
<tr class="even">
<td>加速比</td>
<td style="text-align: right;">1x</td>
<td style="text-align: right;">0.984x</td>
<td style="text-align: right;">1.012x</td>
<td style="text-align: right;">1.013x</td>
</tr>
<tr class="odd">
<td>MaxFlops APE</td>
<td style="text-align: right;">2.82%</td>
<td style="text-align: right;">2.82%</td>
<td style="text-align: right;">28.97%</td>
<td style="text-align: right;">28.97%</td>
</tr>
<tr class="even">
<td>MaxFlops 加速比</td>
<td style="text-align: right;">1x</td>
<td style="text-align: right;">1x</td>
<td style="text-align: right;">1.44x</td>
<td style="text-align: right;">1.44x</td>
</tr>
<tr class="odd">
<td>Cutlass APE</td>
<td style="text-align: right;">9.72%</td>
<td style="text-align: right;">39.35%</td>
<td style="text-align: right;">0.97%</td>
<td style="text-align: right;">2.3%</td>
</tr>
<tr class="even">
<td>Cutlass 加速比</td>
<td style="text-align: right;">1x</td>
<td style="text-align: right;">0.79x</td>
<td style="text-align: right;">1.11x</td>
<td style="text-align: right;">1.12x</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>对 <code>MaxFlops</code> 而言，RFC 是否存在对性能影响不大，因为仅有一条静态指令使用 RFC。但当每 bank 读端口数增至 2（总共 4 个读端口）时，性能提升约 44%，因为每条指令常有 3 个操作数。相对地，从仿真准确性角度看，2 端口配置偏差明显。</p>
<p>对 Cutlass（<code>sgemm</code>）而言，单端口且无 RFC 会导致性能显著下降（0.78x），与程序中约 35.9% 的静态指令至少有一个操作数使用 RFC 的观察一致。引入每 bank 2 个读端口则提升约 12% 性能，说明寄存器文件与缓存结构仍有优化空间。</p>
<p>总之，寄存器文件架构及其缓存对个别基准影响显著，准确建模十分关键。平均而言，单端口 + 简单缓存已接近“无限端口”效果，但对某些基准差距仍很大，值得进一步研究。</p>
</section>
<section id="sec-deps-analysis" class="level2">
<h2 class="anchored" data-anchor-id="sec-deps-analysis">依赖管理机制分析</h2>
<p>本小节比较本文揭示的软硬协同依赖管理机制与传统记分牌方法在性能与面积上的影响。<a href="#tbl-dependence-checking-mechanisms" class="quarto-xref">表&nbsp;7</a> 给出结果。面积开销相对于一个 SM 的常规寄存器文件（256 KB）。</p>
<div id="tbl-dependence-checking-mechanisms" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-dependence-checking-mechanisms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
表&nbsp;7: 不同依赖管理机制的速度、面积与 MAPE。
</figcaption>
<div aria-describedby="tbl-dependence-checking-mechanisms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>指标</th>
<th style="text-align: right;">控制位方案</th>
<th style="text-align: right;">记分牌（最大消费者 63）</th>
<th style="text-align: right;">记分牌（无限制）</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>加速比</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.97x</td>
<td style="text-align: right;">0.97x</td>
</tr>
<tr class="even">
<td>面积开销</td>
<td style="text-align: right;">0.09%</td>
<td style="text-align: right;">5.32%</td>
<td style="text-align: right;">-</td>
</tr>
<tr class="odd">
<td>MAPE</td>
<td style="text-align: right;">13.98%</td>
<td style="text-align: right;">14.87%</td>
<td style="text-align: right;">14.87%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>传统记分牌机制需要为所有可写寄存器提供条目，即每 warp 332 个条目（255 常规寄存器、63 统一寄存器、7 谓词寄存器、7 统一谓词寄存器）。此外需两个记分牌：一个处理 RAW/WAW，另一个处理 WAR<span class="citation" data-cites="warHazards"><a href="#ref-warHazards" role="doc-biblioref">[17]</a></span>，因为虽然发射顺序严格，但可变延迟指令的读写可能乱序，导致 WAR。WAR 记分牌需要记录每条目消费者数量。若支持最多 63 个消费者，则单 warp 需要 2324 bit（<span class="math inline">\(332 + 332\times log2(63+1)\)</span>）。按 48 个 warp 的 SM 计算，总计 111,552 bit，占寄存器文件面积的 5.32%。</p>
<p>相比之下，本文的软硬协同机制仅需每 warp 6 个 6-bit 依赖计数器、4-bit 停顿计数器与 1-bit Yield，共 41 bit。每个 SM 仅 1968 bit，占寄存器文件面积的 0.09%，远小于记分牌方案。</p>
<p>综上，基于控制位的软硬协同机制在性能与面积上优于其他方案，且面积开销极小。在支持 64 个 warp/SM 的架构（如 Hopper<span class="citation" data-cites="hopperPaper"><a href="#ref-hopperPaper" role="doc-biblioref">[22]</a></span>）中，对比更显著：控制位方案开销为 0.13%，而记分牌方案（63 消费者）为 7.09%。此外，在无法获取控制位的应用场景（如部分 Deepbench 内核）中，使用双记分牌（RAW/WAW 与 WAR）且最大消费者 63 的方案在仿真准确性上与控制位接近，因此是有效替代方案。</p>
</section>
<section id="sec-use-other-archs" class="level2">
<h2 class="anchored" data-anchor-id="sec-use-other-archs">向其他 NVIDIA 架构的可移植性</h2>
<p>本文主要聚焦 Ampere，但结论同样适用于 Turing 等架构。除四种 Ampere GPU 的结果外，<a href="#tbl-gpus-specs-and-results" class="quarto-xref">表&nbsp;4</a> 还给出 Turing GPU 结果，显示对 NVIDIA RTX 2080 Ti 的 MAPE 相比 Accel-Sim 提升 6.94%。</p>
<p>虽然我们仅在 Turing 与 Ampere 上验证了模型，但认为其结论可适用于更广泛的 NVIDIA 架构。公开资料与 SM 结构图显示，近期架构的重大变化主要集中在张量核心、光线追踪单元，以及如 TPC 内 SM 之间共享内存的分布式特性等小幅改动<span class="citation" data-cites="hopperPaper"><a href="#ref-hopperPaper" role="doc-biblioref">[22]</a></span>。不过，为适配其他架构仍需重新估计部分指令（如内存指令）的延迟。</p>
</section>
</section>
<section id="sec-relatedwork" class="level1">
<h1>相关工作</h1>
<p>模拟器是学术界与工业界评估体系结构设计的主要工具<span class="citation" data-cites="SimSurvey"><a href="#ref-SimSurvey" role="doc-biblioref">[70]</a></span>，因为其成本低且可用于验证设计与真实硬件的接近程度。GPGPU 亦不例外。NVIDIA 公开了其内部模拟器（NVArchSim/NVAS）的部分开发过程<span class="citation" data-cites="NVAS"><a href="#ref-NVAS" role="doc-biblioref">[71]</a></span>。学术界广泛使用两类公开模拟器：MGPUSim<span class="citation" data-cites="mgpusim"><a href="#ref-mgpusim" role="doc-biblioref">[72]</a></span>（建模 AMD GCN 3，面向支持虚拟内存的多 GPU 系统）与 Accel-Sim<span class="citation" data-cites="accelsim"><a href="#ref-accelsim" role="doc-biblioref">[13]</a></span>（基于 GPGPU-Sim 3<span class="citation" data-cites="gpgpusim3"><a href="#ref-gpgpusim3" role="doc-biblioref">[12]</a></span> 的周期级 trace 驱动模拟器，支持 CUDA 且建模类似 NVIDIA 的现代架构）。</p>
<p>在 CPU 领域，有许多逆向研究，例如 Intel 分支预测器<span class="citation" data-cites="intelBranchPredictor"><a href="#ref-intelBranchPredictor" role="doc-biblioref">[73]</a></span>与缓存设计<span class="citation" data-cites="intelReverseCacheAddress intelReverseCacheSlice"><a href="#ref-intelReverseCacheAddress" role="doc-biblioref">[74]</a>, <a href="#ref-intelReverseCacheSlice" role="doc-biblioref">[75]</a></span>。</p>
<p>针对 NVIDIA GPU，已有不少工作聚焦于特定组件：Ahn 等<span class="citation" data-cites="reverseNoc"><a href="#ref-reverseNoc" role="doc-biblioref">[76]</a></span>与 Jin 等<span class="citation" data-cites="UncoveringNOC"><a href="#ref-UncoveringNOC" role="doc-biblioref">[77]</a></span>逆向 Volta 与 Ampere 的片上网络；Lashgar 等<span class="citation" data-cites="reverseMshrPRT"><a href="#ref-reverseMshrPRT" role="doc-biblioref">[78]</a></span>研究 Fermi 与 Kepler 处理内存请求的能力；Jia 等<span class="citation" data-cites="dissectingVolta dissectingTuring"><a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>揭示缓存行大小、相联度、指令延迟与寄存器文件细节；Khairy 等<span class="citation" data-cites="voltaCaches"><a href="#ref-voltaCaches" role="doc-biblioref">[79]</a></span>研究 Volta 的 L1 与 L2 缓存；Abdelkhalik 等<span class="citation" data-cites="demystifyingAmpere"><a href="#ref-demystifyingAmpere" role="doc-biblioref">[57]</a></span>建立了 Ampere 的 PTX 与 SASS 关系及执行延迟；张量核心方面已有多项工作<span class="citation" data-cites="dissectingVolta dissecTensorCoresVolta1 dissecTensorCoresVolta2 dissectingTuring dissecTensorCoresTuringVolta1 dissecTensorCoresTuringVolta2 dissecTensorCoresAmpere1 dissecTensorCoresAmpere2"><a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a>, <a href="#ref-dissecTensorCoresVolta1" role="doc-biblioref">[80]</a>, <a href="#ref-dissecTensorCoresVolta2" role="doc-biblioref">[81]</a>, <a href="#ref-dissecTensorCoresTuringVolta1" role="doc-biblioref">[82]</a>, <a href="#ref-dissecTensorCoresTuringVolta2" role="doc-biblioref">[83]</a>, <a href="#ref-dissecTensorCoresAmpere1" role="doc-biblioref">[84]</a>, <a href="#ref-dissecTensorCoresAmpere2" role="doc-biblioref">[85]</a></span>；张等<span class="citation" data-cites="tunnelsTLB"><a href="#ref-tunnelsTLB" role="doc-biblioref">[86]</a></span>逆向 Turing/Ampere TLB 以进行 Multi-Instance GPU 攻击；Shoushtary 等<span class="citation" data-cites="mojtabaControlFlow"><a href="#ref-mojtabaControlFlow" role="doc-biblioref">[47]</a></span>用 1.03% 误差提出 Turing 控制流指令的语义；Amert 等<span class="citation" data-cites="reverseTX2"><a href="#ref-reverseTX2" role="doc-biblioref">[87]</a></span>研究 NVIDIA Jetson TX2 中 GPU 任务调度与 ARM CPU 交互；Wong 等<span class="citation" data-cites="demystifyingGPU"><a href="#ref-demystifyingGPU" role="doc-biblioref">[88]</a></span>描述 Tesla 早期架构的缓存、TLB、SIMT 控制流与 CTA barrier。</p>
<p>关于其他 GPU 厂商，Gutierrez 等<span class="citation" data-cites="amdGap1"><a href="#ref-amdGap1" role="doc-biblioref">[89]</a></span>指出使用 AMD GPU 机器 ISA 而非中间语言对准确评估瓶颈与优化至关重要。GAP 工具<span class="citation" data-cites="amdGap2"><a href="#ref-amdGap2" role="doc-biblioref">[90]</a></span>揭示真实 AMD GPU 与 gem5 模拟之间的不一致，推动了 gem5 对 AMD GPU 的改进<span class="citation" data-cites="amdGap3 amdGap4"><a href="#ref-amdGap3" role="doc-biblioref">[91]</a>, <a href="#ref-amdGap4" role="doc-biblioref">[92]</a></span>。Gera 等<span class="citation" data-cites="intelGPUs"><a href="#ref-intelGPUs" role="doc-biblioref">[93]</a></span>提出 Intel 集成 GPU 的模拟框架与特性分析。</p>
<p>编译器提示（控制位）至少从 NVIDIA Kepler 架构就已使用<span class="citation" data-cites="KeplerASPaper KeplerASRepo"><a href="#ref-KeplerASRepo" role="doc-biblioref">[27]</a>, <a href="#ref-KeplerASPaper" role="doc-biblioref">[28]</a></span>，Gray 等<span class="citation" data-cites="maxas"><a href="#ref-maxas" role="doc-biblioref">[26]</a></span>公开描述了其细节。在 Kepler/Maxwell/Pascal 中，平均每 3 到 7 条指令就有一条是编译器插入的提示指令。Jia 等<span class="citation" data-cites="dissectingVolta dissectingTuring"><a href="#ref-dissectingVolta" role="doc-biblioref">[32]</a>, <a href="#ref-dissectingTuring" role="doc-biblioref">[33]</a></span>指出新架构将指令位宽从 64 扩展到 128 bit，使得提示位内嵌于每条指令中。这些提示位既用于优化性能，也用于避免数据冒险以保证正确性。CPU 也使用编译器提示辅助硬件资源管理<span class="citation" data-cites="HardwareAwareCompilation"><a href="#ref-HardwareAwareCompilation" role="doc-biblioref">[94]</a></span>，如旁路、分支预测、缓存等。</p>
<p>据我们所知，本文首次揭示现代 NVIDIA GPU 核心微架构，并构建高准确度的微架构仿真模型。我们发现的关键新特性包括：控制位语义及其支持的微架构改变、发射调度器行为、寄存器文件及其缓存结构、内存流水线多个重要细节。这些因素对准确建模现代 NVIDIA GPU 至关重要。</p>
</section>
<section id="sec-conclusion" class="level1">
<h1>结论</h1>
<p>本文通过在真实硬件上的逆向分析，揭示了现代 NVIDIA GPU 微架构。我们剖析了发射阶段逻辑，分析了 warp 就绪条件，并发现 warp 间发射调度遵循 CGGTY 策略；揭示了寄存器文件的端口数量与宽度，以及寄存器文件缓存的行为；分析了内存流水线的重要特性，如 load/store 队列大小、sub-core 间争用以及不同粒度访问对延迟的影响；并提出满足现代 NVIDIA GPU 需求的取指阶段设计。</p>
<p>本文还系统整理并扩展了控制位的公开信息。</p>
<p>此外，我们在模拟器中建模了这些细节，并与真实硬件对比，证明其在执行周期准确性上比以往模型提升超过 18.24%。</p>
<p>我们进一步展示，使用简单流缓冲的指令预取在准确性与性能上接近完美指令缓存；控制位驱动的依赖管理机制优于传统记分牌。</p>
<p>最后，我们分析了寄存器文件缓存与读端口数量对仿真准确性与性能的影响。</p>
<p>总体而言，GPU 是一种硬件—编译器协同设计：编译器引导硬件处理依赖，并通过提示位改进性能与能耗。</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">参考文献</h2><div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<div id="ref-usageOfGPUs" class="csl-entry" role="listitem">
<div class="csl-left-margin">[1] </div><div class="csl-right-inline">M. Burtscher, R. Nasre, 和 K. Pingali, <span>《<span>A quantitative study of irregular programs on GPUs</span>》</span>, 收入 <em>Proceedings - 2012 IEEE International Symposium on Workload Characterization, IISWC 2012</em>, 2012, 页 141–151. doi: <a href="https://doi.org/10.1109/IISWC.2012.6402918">10.1109/IISWC.2012.6402918</a>.</div>
</div>
<div id="ref-cudaInGPUS" class="csl-entry" role="listitem">
<div class="csl-left-margin">[2] </div><div class="csl-right-inline">M. S. Nobile, P. Cazzaniga, A. Tangherloni, 和 D. Besozzi, <span>《<span>Graphics processing units in bioinformatics, computational biology and systems biology</span>》</span>, <em>Briefings in Bioinformatics</em>, 卷 18, 期 5, 页 870–885, 7月 2016, doi: <a href="https://doi.org/10.1093/bib/bbw058">10.1093/bib/bbw058</a>.</div>
</div>
<div id="ref-markovGPUBioinformatics" class="csl-entry" role="listitem">
<div class="csl-left-margin">[3] </div><div class="csl-right-inline">A. Bustamam, K. Burrage, 和 N. A. Hamilton, <span>《<span>Fast Parallel Markov Clustering in Bioinformatics Using Massively Parallel Computing on GPU with CUDA and ELLPACK-R Sparse Format</span>》</span>, <em>IEEE/ACM Transactions on Computational Biology and Bioinformatics</em>, 卷 9, 期 3, 页 679–692, 2012, doi: <a href="https://doi.org/10.1109/TCBB.2011.68">10.1109/TCBB.2011.68</a>.</div>
</div>
<div id="ref-molecularPhysicsCuda" class="csl-entry" role="listitem">
<div class="csl-left-margin">[4] </div><div class="csl-right-inline">W. Liu, B. Schmidt, G. Voss, 和 W. Müller-Wittig, <span>《<span>Accelerating molecular dynamics simulations using Graphics Processing Units with CUDA</span>》</span>, <em>Computer Physics Communications</em>, 卷 179, 期 9, 页 634–641, 2008, doi: <a href="https://doi.org/10.1016/j.cpc.2008.05.008">https://doi.org/10.1016/j.cpc.2008.05.008</a>.</div>
</div>
<div id="ref-fdtdPhysicsCuda" class="csl-entry" role="listitem">
<div class="csl-left-margin">[5] </div><div class="csl-right-inline">C. Warren <em>等</em>, <span>《<span>A CUDA-based GPU engine for gprMax: Open source FDTD electromagnetic simulation software</span>》</span>, <em>Computer Physics Communications</em>, 卷 237, 页 208–218, 2019, doi: <a href="https://doi.org/10.1016/j.cpc.2018.11.007">https://doi.org/10.1016/j.cpc.2018.11.007</a>.</div>
</div>
<div id="ref-detailedChemistry" class="csl-entry" role="listitem">
<div class="csl-left-margin">[6] </div><div class="csl-right-inline">F. E. Hernández Pérez <em>等</em>, <span>《<span>Direct numerical simulations of reacting flows with detailed chemistry using many-core/GPU acceleration</span>》</span>, <em>Computers &amp; Fluids</em>, 卷 173, 页 73–79, 2018, doi: <a href="https://doi.org/10.1016/j.compfluid.2018.03.074">https://doi.org/10.1016/j.compfluid.2018.03.074</a>.</div>
</div>
<div id="ref-cheminformaticsGPU" class="csl-entry" role="listitem">
<div class="csl-left-margin">[7] </div><div class="csl-right-inline">J. L. Xiaoxia Li Zheng Mo 和 L. Guo, <span>《´Revealing chemical reactions of coal pyrolysis with GPU-enabled ReaxFF molecular dynamics and cheminformatics analysis》</span>.</div>
</div>
<div id="ref-cuDNNLibraryIA" class="csl-entry" role="listitem">
<div class="csl-left-margin">[8] </div><div class="csl-right-inline">S. Chetlur <em>等</em>, <span>《<span>cuDNN: Efficient Primitives for Deep Learning</span>》</span>, 10月 2014, doi: <a href="https://doi.org/10.48550/arxiv.1410.0759">10.48550/arxiv.1410.0759</a>.</div>
</div>
<div id="ref-nvlink" class="csl-entry" role="listitem">
<div class="csl-left-margin">[9] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA NVLink TM High-Speed Interconnect: Application Performance</span>》</span>, Nvidia, 2014.</div>
</div>
<div id="ref-nccl" class="csl-entry" role="listitem">
<div class="csl-left-margin">[10] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA Collective Communications Library (NCCL)</span>》</span>. <a href="https://developer.nvidia.com/nccl" class="uri">https://developer.nvidia.com/nccl</a>, 2016年.</div>
</div>
<div id="ref-articuloWebMSNumGPUsIA" class="csl-entry" role="listitem">
<div class="csl-left-margin">[11] </div><div class="csl-right-inline">Microsoft, <span>《<span>How Microsoft’s bet on Azure unlocked an AI revolution.</span>》</span> <a href="https://news.microsoft.com/source/features/ai/how-microsofts-bet-on-azure-unlocked-an-ai-revolution/" class="uri">https://news.microsoft.com/source/features/ai/how-microsofts-bet-on-azure-unlocked-an-ai-revolution/</a>, 2023年.</div>
</div>
<div id="ref-gpgpusim3" class="csl-entry" role="listitem">
<div class="csl-left-margin">[12] </div><div class="csl-right-inline">A. Bakhoda, G. L. Yuan, W. W. L. Fung, H. Wong, 和 T. M. Aamodt, <span>《<span>Analyzing CUDA workloads using a detailed GPU simulator</span>》</span>, 收入 <em>2009 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)</em>, 2009, 页 163–174. doi: <a href="https://doi.org/10.1109/ISPASS.2009.4919648">10.1109/ISPASS.2009.4919648</a>.</div>
</div>
<div id="ref-accelsim" class="csl-entry" role="listitem">
<div class="csl-left-margin">[13] </div><div class="csl-right-inline">M. Khairy, Z. Shen, T. M. Aamodt, 和 T. G. Rogers, <span>《<span>Accel-Sim: An Extensible Simulation Framework for Validated GPU Modeling</span>》</span>, 收入 <em>2020 ACM/IEEE 47th Annual International Symposium on Computer Architecture (ISCA)</em>, 5月 2020, 页 473–486. doi: <a href="https://doi.org/10.1109/ISCA45697.2020.00047">10.1109/ISCA45697.2020.00047</a>.</div>
</div>
<div id="ref-teslaHotchips" class="csl-entry" role="listitem">
<div class="csl-left-margin">[14] </div><div class="csl-right-inline">E. Lindholm, J. Nickolls, S. Oberman, 和 J. Montrym, <span>《<span>NVIDIA Tesla: A Unified Graphics and Computing Architecture</span>》</span>, <em>IEEE Micro</em>, 卷 28, 期 2, 页 39–55, 2008, doi: <a href="https://doi.org/10.1109/MM.2008.31">10.1109/MM.2008.31</a>.</div>
</div>
<div id="ref-gpgpuBook" class="csl-entry" role="listitem">
<div class="csl-left-margin">[15] </div><div class="csl-right-inline">T. M. Aamodt, W. W. L. Fung, 和 T. G. Rogers, <em><span>General-purpose Graphics Processor Architectures</span></em>. Morgan &amp; Claypool Publishers, 2018.</div>
</div>
<div id="ref-GTO" class="csl-entry" role="listitem">
<div class="csl-left-margin">[16] </div><div class="csl-right-inline">T. G. Rogers, M. Oconnor, 和 T. M. Aamodt, <span>《<span>Cache-conscious wavefront scheduling</span>》</span>, 收入 <em>Proceedings - 2012 IEEE/ACM 45th International Symposium on Microarchitecture, MICRO 2012</em>, IEEE Computer Society, 2012, 页 72–83. doi: <a href="https://doi.org/10.1109/MICRO.2012.16">10.1109/MICRO.2012.16</a>.</div>
</div>
<div id="ref-warHazards" class="csl-entry" role="listitem">
<div class="csl-left-margin">[17] </div><div class="csl-right-inline">M. Mishkin, <span>《<span>Write-after-Read Hazard Prevention in GPGPUsim</span>》</span>, 2016.</div>
</div>
<div id="ref-IPOLYPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[18] </div><div class="csl-right-inline">B. R. Rau, <span>《Pseudo-randomly interleaved memory》</span>, 收入 <em>Proceedings of the 18th Annual International Symposium on Computer Architecture</em>, 收入 ISCA ’91. New York, NY, USA: Association for Computing Machinery, 1991, 页 74–83. doi: <a href="https://doi.org/10.1145/115952.115961">10.1145/115952.115961</a>.</div>
</div>
<div id="ref-voltaPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[19] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA Tesla V100 GPU architecture the world’s most advanced data center GPU</span>》</span>, NVIDIA, 2017.</div>
</div>
<div id="ref-turingPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[20] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA TURING GPU architecture Graphics Reinvented NVIDIA Turing GPU Architecture</span>》</span>, NVIDIA, 2018.</div>
</div>
<div id="ref-amperePaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[21] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA AMPERE GA102 GPU architecture Second-Generation RTX NVIDIA Ampere GA102 GPU Architecture</span>》</span>, NVIDIA, 2020.</div>
</div>
<div id="ref-hopperPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[22] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA H100 Tensor Core GPU Architecture</span>》</span>, NVIDIA, 2022.</div>
</div>
<div id="ref-adaPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[23] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA ADA GPU architecture</span>》</span>, NVIDIA, 2022.</div>
</div>
<div id="ref-voltaHotChips" class="csl-entry" role="listitem">
<div class="csl-left-margin">[24] </div><div class="csl-right-inline">J. Choquette, O. Giroux, 和 D. Foley, <span>《<span>Volta: Performance and Programmability</span>》</span>, <em>IEEE Micro</em>, 卷 38, 期 2, 页 42–52, 2018, doi: <a href="https://doi.org/10.1109/MM.2018.022071134">10.1109/MM.2018.022071134</a>.</div>
</div>
<div id="ref-turingHotChips" class="csl-entry" role="listitem">
<div class="csl-left-margin">[25] </div><div class="csl-right-inline">J. Burgess, <span>《<span>RTX on—The NVIDIA Turing GPU</span>》</span>, <em>IEEE Micro</em>, 卷 40, 期 2, 页 36–44, 2020, doi: <a href="https://doi.org/10.1109/MM.2020.2971677">10.1109/MM.2020.2971677</a>.</div>
</div>
<div id="ref-maxas" class="csl-entry" role="listitem">
<div class="csl-left-margin">[26] </div><div class="csl-right-inline">S. Gray, <span>《<span>MaxAS: Assembler for NVIDIA Maxwell architecture</span>》</span>. 载于: <a href="https://github.com/NervanaSystems/maxas">https://github.com/NervanaSystems/maxas</a></div>
</div>
<div id="ref-KeplerASRepo" class="csl-entry" role="listitem">
<div class="csl-left-margin">[27] </div><div class="csl-right-inline">X. Zhang, <span>《<span>KeplerAs: An Open Source Kepler GPU Assembler</span>》</span>. 载于: <a href="https://github.com/xiuxiazhang/KeplerAs">https://github.com/xiuxiazhang/KeplerAs</a></div>
</div>
<div id="ref-KeplerASPaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[28] </div><div class="csl-right-inline">X. Zhang, G. Tan, S. Xue, J. Li, K. Zhou, 和 M. Chen, <span>《<span>Understanding the GPU Microarchitecture to Achieve Bare-Metal Performance Tuning</span>》</span>, 收入 <em>Proceedings of the 22nd ACM SIGPLAN Symposium on Principles and Practice of Parallel Programming</em>, 收入 PPoPP ’17. New York, NY, USA: Association for Computing Machinery, 2017, 页 31–43. doi: <a href="https://doi.org/10.1145/3018743.3018755">10.1145/3018743.3018755</a>.</div>
</div>
<div id="ref-turingas" class="csl-entry" role="listitem">
<div class="csl-left-margin">[29] </div><div class="csl-right-inline">D. Yan, <span>《<span>TuringAS: Assembler for NVIDIA Volta and Turing GPUs</span>》</span>. 载于: <a href="https://github.com/daadaada/turingas">https://github.com/daadaada/turingas</a></div>
</div>
<div id="ref-CuAssembler" class="csl-entry" role="listitem">
<div class="csl-left-margin">[30] </div><div class="csl-right-inline">Cloudcores, <span>《<span>CuAssembler: An unofficial cuda assembler, for all generations of SASS</span>》</span>. 载于: <a href="https://github.com/cloudcores/CuAssembler">https://github.com/cloudcores/CuAssembler</a></div>
</div>
<div id="ref-gtx680WhitePaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[31] </div><div class="csl-right-inline">NVIDIA, <span>《<span>Technology Overview NVIDIA GeForce GTX 680</span>》</span>, NVIDIA, 2012.</div>
</div>
<div id="ref-dissectingVolta" class="csl-entry" role="listitem">
<div class="csl-left-margin">[32] </div><div class="csl-right-inline">Z. Jia, M. Maggioni, B. Staiger, 和 D. P. Scarpazza, <span>《<span>Dissecting the NVIDIA Volta GPU Architecture via Microbenchmarking</span>》</span>, <em>CoRR</em>, 卷 abs/1804.06826, 2018, 载于: <a href="http://arxiv.org/abs/1804.06826">http://arxiv.org/abs/1804.06826</a></div>
</div>
<div id="ref-dissectingTuring" class="csl-entry" role="listitem">
<div class="csl-left-margin">[33] </div><div class="csl-right-inline">Z. Jia, M. Maggioni, J. Smith, 和 D. P. Scarpazza, <span>《<span>Dissecting the NVIDIA Turing T4 GPU via Microbenchmarking Technical Report</span>》</span>, 2019.</div>
</div>
<div id="ref-amdCDNA1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[34] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"AMD Instinct MI100" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2020.</div>
</div>
<div id="ref-amdCDNA2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[35] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"AMD Instinct MI200" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2022.</div>
</div>
<div id="ref-amdCDNA3" class="csl-entry" role="listitem">
<div class="csl-left-margin">[36] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"AMD Instinct MI300" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2024.</div>
</div>
<div id="ref-amdRDNA1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[37] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"RDNA 1.0" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2020.</div>
</div>
<div id="ref-amdRDNA2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[38] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"RDNA 2" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2020.</div>
</div>
<div id="ref-amdRDNA35" class="csl-entry" role="listitem">
<div class="csl-left-margin">[39] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"RDNA 3.5" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2024.</div>
</div>
<div id="ref-amdRDNA3" class="csl-entry" role="listitem">
<div class="csl-left-margin">[40] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">"RDNA 3" Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2023.</div>
</div>
<div id="ref-amdVega7nm" class="csl-entry" role="listitem">
<div class="csl-left-margin">[41] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">Vega 7nm Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2020.</div>
</div>
<div id="ref-amdGCN3" class="csl-entry" role="listitem">
<div class="csl-left-margin">[42] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">AMD Graphics Core Next Architecture, Generation 3. Reference Guide.</span></span>》</span>, AMD, 2016.</div>
</div>
<div id="ref-amdVega" class="csl-entry" role="listitem">
<div class="csl-left-margin">[43] </div><div class="csl-right-inline">AMD, <span>《<span><span style="color: darkerGreen">Vega Instruction Set Architecture. Reference Guide.</span></span>》</span>, AMD, 2020.</div>
</div>
<div id="ref-nvidiaInstPrefeching" class="csl-entry" role="listitem">
<div class="csl-left-margin">[44] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA Developer Forums: Instruction cache and instruction fetch stalls</span>》</span>. 载于: <a href="https://forums.developer.nvidia.com/t/instruction-cache-and-instruction-fetch-stalls/76883">https://forums.developer.nvidia.com/t/instruction-cache-and-instruction-fetch-stalls/76883</a></div>
</div>
<div id="ref-GPUinstPrefeching" class="csl-entry" role="listitem">
<div class="csl-left-margin">[45] </div><div class="csl-right-inline">J. Cao, Z. Chen, Y. Wang, H. Guo, 和 P. Wang, <span>《Instruction prefetch for improving GPGPU performance》</span>, <em>IEICE Transactions on Fundamentals of Electronics, Communications and Computer Sciences</em>, 卷 E104A, 页 773–785, 2021, doi: <a href="https://doi.org/10.1587/TRANSFUN.2020EAP1105">10.1587/TRANSFUN.2020EAP1105</a>.</div>
</div>
<div id="ref-streamBufferPrefetching" class="csl-entry" role="listitem">
<div class="csl-left-margin">[46] </div><div class="csl-right-inline">N. P. Jouppi, <span>《Improving direct-mapped cache performance by the addition of a small fully-associative cache and prefetch buffers》</span>, 收入 <em>1990 17th Annual International Symposium on Computer Architecture</em>, 1990, 页 364–373. doi: <a href="https://doi.org/10.1109/ISCA.1990.134547">10.1109/ISCA.1990.134547</a>.</div>
</div>
<div id="ref-mojtabaControlFlow" class="csl-entry" role="listitem">
<div class="csl-left-margin">[47] </div><div class="csl-right-inline">M. A. Shoushtary, J. T. Murgadas, 和 A. Gonzalez, <span>《<span>Control Flow Management in Modern GPUs</span>》</span>. 2024年. 载于: <a href="https://arxiv.org/abs/2407.02944">https://arxiv.org/abs/2407.02944</a></div>
</div>
<div id="ref-GPU2OcusSubcore" class="csl-entry" role="listitem">
<div class="csl-left-margin">[48] </div><div class="csl-right-inline">A. Barnes, F. Shen, 和 T. G. Rogers, <span>《<span>Mitigating GPU Core Partitioning Performance Effects</span>》</span>, 收入 <em>2023 IEEE International Symposium on High-Performance Computer Architecture (HPCA)</em>, 2023, 页 530–542. doi: <a href="https://doi.org/10.1109/HPCA56546.2023.10070957">10.1109/HPCA56546.2023.10070957</a>.</div>
</div>
<div id="ref-fermiWhitePaper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[49] </div><div class="csl-right-inline">NVIDIA, <span>《<span>NVIDIA’s Next Generation CUDA TM Compute Architecture: Fermi</span>》</span>, NVIDIA, 2009.</div>
</div>
<div id="ref-registerFileCacheFirst" class="csl-entry" role="listitem">
<div class="csl-left-margin">[50] </div><div class="csl-right-inline">M. Gebhart <em>等</em>, <span>《Energy-efficient mechanisms for managing thread context in throughput processors》</span>, 收入 <em>2011 38th Annual International Symposium on Computer Architecture (ISCA)</em>, 2011, 页 235–246. doi: <a href="https://doi.org/10.1145/2000064.2000093">10.1145/2000064.2000093</a>.</div>
</div>
<div id="ref-registerFileCacheSimilar" class="csl-entry" role="listitem">
<div class="csl-left-margin">[51] </div><div class="csl-right-inline">M. Gebhart, S. W. Keckler, 和 W. J. Dally, <span>《<a href="">A compile-time managed multi-level register file hierarchy</a>》</span>, 收入 <em>2011 44th Annual IEEE/ACM International Symposium on Microarchitecture (MICRO)</em>, 2011, 页 465–476.</div>
</div>
<div id="ref-BOW" class="csl-entry" role="listitem">
<div class="csl-left-margin">[52] </div><div class="csl-right-inline">H. A. Esfeden, A. Abdolrashidi, S. Rahman, D. Wong, 和 N. Abu-Ghazaleh, <span>《<span>BOW: Breathing Operand Windows to Exploit Bypassing in GPUs</span>》</span>, 收入 <em>2020 53rd Annual IEEE/ACM International Symposium on Microarchitecture (MICRO)</em>, 2020, 页 996–1008. doi: <a href="https://doi.org/10.1109/MICRO50266.2020.00084">10.1109/MICRO50266.2020.00084</a>.</div>
</div>
<div id="ref-ltrf" class="csl-entry" role="listitem">
<div class="csl-left-margin">[53] </div><div class="csl-right-inline">M. Sadrosadati <em>等</em>, <span>《<span>LTRF: Enabling High-Capacity Register Files for GPUs via Hardware/Software Cooperative Register Prefetching</span>》</span>, 收入 <em>Proceedings of the Twenty-Third International Conference on Architectural Support for Programming Languages and Operating Systems</em>, 收入 ASPLOS ’18. New York, NY, USA: Association for Computing Machinery, 2018, 页 489–502. doi: <a href="https://doi.org/10.1145/3173162.3173211">10.1145/3173162.3173211</a>.</div>
</div>
<div id="ref-mojtabaIsca" class="csl-entry" role="listitem">
<div class="csl-left-margin">[54] </div><div class="csl-right-inline">M. Abaie Shoushtary, J. M. Arnau, J. Tubella Murgadas, 和 A. Gonzalez, <span>《<a href=""><span>Memento: An Adaptive, Compiler-Assisted Register File Cache for GPUs</span></a>》</span>, 收入 <em>2024 ACM/IEEE 51th Annual International Symposium on Computer Architecture (ISCA)</em>, 2024.</div>
</div>
<div id="ref-patentLDGSTS" class="csl-entry" role="listitem">
<div class="csl-left-margin">[55] </div><div class="csl-right-inline">S. J. Heinrich 和 A. L. Madison, <span>《Techniques for efficiently transferring data to a processor》</span>, 卷 417, 2019.</div>
</div>
<div id="ref-dissectingAmpere" class="csl-entry" role="listitem">
<div class="csl-left-margin">[56] </div><div class="csl-right-inline">Z. Jia 和 P. V. Sandt, <span>《<span>Dissecting the Ampere GPU Architecture through Microbenchmarking</span>》</span>, 收入 <em>NVIDIA GTC 2021</em>, <span>NVIDIA</span>, 2021. 载于: <a href="https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s33322/">https://www.nvidia.com/en-us/on-demand/session/gtcspring21-s33322/</a></div>
</div>
<div id="ref-demystifyingAmpere" class="csl-entry" role="listitem">
<div class="csl-left-margin">[57] </div><div class="csl-right-inline">H. Abdelkhalik, Y. Arafa, N. Santhi, 和 A.-H. A. Badawy, <span>《<span>Demystifying the Nvidia Ampere Architecture through Microbenchmarking and Instruction-level Analysis</span>》</span>, 收入 <em>2022 IEEE High Performance Extreme Computing Conference (HPEC)</em>, 2022, 页 1–8. doi: <a href="https://doi.org/10.1109/HPEC55821.2022.9926299">10.1109/HPEC55821.2022.9926299</a>.</div>
</div>
<div id="ref-cams2023paper" class="csl-entry" role="listitem">
<div class="csl-left-margin">[58] </div><div class="csl-right-inline">R. Huerta, M. A. Shoushtary, 和 A. González, <span>《<span>Analyzing and Improving Hardware Modeling of Accel-Sim</span>》</span>. 2024年. 载于: <a href="https://arxiv.org/abs/2401.10082">https://arxiv.org/abs/2401.10082</a></div>
</div>
<div id="ref-cudaBinaryUtils" class="csl-entry" role="listitem">
<div class="csl-left-margin">[59] </div><div class="csl-right-inline">NVIDIA, <span>《<span>CUDA binary utilities documentation</span>》</span>. n.d. 载于: <a href="https://docs.nvidia.com/cuda/cuda-binary-utilities/">https://docs.nvidia.com/cuda/cuda-binary-utilities/</a></div>
</div>
<div id="ref-cutlass" class="csl-entry" role="listitem">
<div class="csl-left-margin">[60] </div><div class="csl-right-inline">NVIDIA, <span>《<span>CUTLASS: CUDA Templates for Linear Algebra Subroutines</span>》</span>. n.d. 载于: <a href="https://github.com/NVIDIA/cutlass">https://github.com/NVIDIA/cutlass</a></div>
</div>
<div id="ref-deepbenchWeb" class="csl-entry" role="listitem">
<div class="csl-left-margin">[61] </div><div class="csl-right-inline">S. Narang 和 G. Diamos, <span>《<span>DeepBench: Benchmarking Deep Learning operations on different hardware</span>》</span>. 2016年. 见于: 2022年4月21日. [在线]. 载于: <a href="https://github.com/baidu-research/DeepBench">https://github.com/baidu-research/DeepBench</a></div>
</div>
<div id="ref-dragon" class="csl-entry" role="listitem">
<div class="csl-left-margin">[62] </div><div class="csl-right-inline">J. Wang 和 S. Yalamanchili, <span>《<span>Characterization and analysis of dynamic parallelism in unstructured GPU applications</span>》</span>, 收入 <em>2014 IEEE International Symposium on Workload Characterization (IISWC)</em>, 2014, 页 51–60. doi: <a href="https://doi.org/10.1109/IISWC.2014.6983039">10.1109/IISWC.2014.6983039</a>.</div>
</div>
<div id="ref-lonestar" class="csl-entry" role="listitem">
<div class="csl-left-margin">[63] </div><div class="csl-right-inline">M. Burtscher, R. Nasre, 和 K. Pingali, <span>《<span>A quantitative study of irregular programs on GPUs</span>》</span>, 收入 <em>2012 IEEE International Symposium on Workload Characterization (IISWC)</em>, 2012, 页 141–151. doi: <a href="https://doi.org/10.1109/IISWC.2012.6402918">10.1109/IISWC.2012.6402918</a>.</div>
</div>
<div id="ref-pannotia" class="csl-entry" role="listitem">
<div class="csl-left-margin">[64] </div><div class="csl-right-inline">S. Che, B. M. Beckmann, S. K. Reinhardt, 和 K. Skadron, <span>《<span>Pannotia: Understanding irregular GPGPU graph applications</span>》</span>, 收入 <em>2013 IEEE International Symposium on Workload Characterization (IISWC)</em>, 2013, 页 185–195. doi: <a href="https://doi.org/10.1109/IISWC.2013.6704684">10.1109/IISWC.2013.6704684</a>.</div>
</div>
<div id="ref-parboil" class="csl-entry" role="listitem">
<div class="csl-left-margin">[65] </div><div class="csl-right-inline">J. A. Stratton <em>等</em>, <span>《<span>Parboil: A Revised Benchmark Suite for Scientific and Commercial Throughput Computing</span>》</span>, <em>Center for Reliable and High-Performance Computing</em>, 2012.</div>
</div>
<div id="ref-polybench" class="csl-entry" role="listitem">
<div class="csl-left-margin">[66] </div><div class="csl-right-inline">S. Grauer-Gray, L. Xu, R. Searles, S. Ayalasomayajula, 和 J. Cavazos, <span>《<span>Auto-tuning a high-level language targeted to GPU codes</span>》</span>, 收入 <em>2012 Innovative Parallel Computing (InPar)</em>, 2012, 页 1–10. doi: <a href="https://doi.org/10.1109/InPar.2012.6339595">10.1109/InPar.2012.6339595</a>.</div>
</div>
<div id="ref-proxy" class="csl-entry" role="listitem">
<div class="csl-left-margin">[67] </div><div class="csl-right-inline">O. Villa <em>等</em>, <span>《<span>Scaling the Power Wall: A Path to Exascale</span>》</span>, 收入 <em>SC ’14: Proceedings of the International Conference for High Performance Computing, Networking, Storage and Analysis</em>, 2014, 页 830–841. doi: <a href="https://doi.org/10.1109/SC.2014.73">10.1109/SC.2014.73</a>.</div>
</div>
<div id="ref-rodinia" class="csl-entry" role="listitem">
<div class="csl-left-margin">[68] </div><div class="csl-right-inline">S. Che <em>等</em>, <span>《<span>Rodinia: A benchmark suite for heterogeneous computing</span>》</span>, 收入 <em>Proceedings of the 2009 IEEE International Symposium on Workload Characterization, IISWC 2009</em>, 2009, 页 44–54. doi: <a href="https://doi.org/10.1109/IISWC.2009.5306797">10.1109/IISWC.2009.5306797</a>.</div>
</div>
<div id="ref-fdpPrefetching" class="csl-entry" role="listitem">
<div class="csl-left-margin">[69] </div><div class="csl-right-inline">G. Reinman, B. Calder, 和 T. Austin, <span>《Fetch directed instruction prefetching》</span>, 收入 <em>MICRO-32. Proceedings of the 32nd Annual ACM/IEEE International Symposium on Microarchitecture</em>, 1999, 页 16–27. doi: <a href="https://doi.org/10.1109/MICRO.1999.809439">10.1109/MICRO.1999.809439</a>.</div>
</div>
<div id="ref-SimSurvey" class="csl-entry" role="listitem">
<div class="csl-left-margin">[70] </div><div class="csl-right-inline">A. Akram 和 L. Sawalha, <span>《<span>A Survey of Computer Architecture Simulation Techniques and Tools</span>》</span>, <em>IEEE Access</em>, 卷 7, 页 78120–78145, 2019, doi: <a href="https://doi.org/10.1109/ACCESS.2019.2917698">10.1109/ACCESS.2019.2917698</a>.</div>
</div>
<div id="ref-NVAS" class="csl-entry" role="listitem">
<div class="csl-left-margin">[71] </div><div class="csl-right-inline">O. Villa <em>等</em>, <span>《<span>Need for Speed: Experiences Building a Trustworthy System-Level GPU Simulator</span>》</span>, 收入 <em>2021 IEEE International Symposium on High-Performance Computer Architecture (HPCA)</em>, 2021, 页 868–880. doi: <a href="https://doi.org/10.1109/HPCA51647.2021.00077">10.1109/HPCA51647.2021.00077</a>.</div>
</div>
<div id="ref-mgpusim" class="csl-entry" role="listitem">
<div class="csl-left-margin">[72] </div><div class="csl-right-inline">Y. Sun <em>等</em>, <span>《<a href=""><span>MGPUSim: Enabling Multi-GPU Performance Modeling and Optimization</span></a>》</span>, 收入 <em>2019 ACM/IEEE 46th Annual International Symposium on Computer Architecture (ISCA)</em>, 2019, 页 197–209.</div>
</div>
<div id="ref-intelBranchPredictor" class="csl-entry" role="listitem">
<div class="csl-left-margin">[73] </div><div class="csl-right-inline">H. Yavarzadeh, M. Taram, S. Narayan, D. Stefan, 和 D. Tullsen, <span>《<span>Half&amp;Half: Demystifying Intel’s Directional Branch Predictors for Fast, Secure Partitioned Execution</span>》</span>, 收入 <em>2023 IEEE Symposium on Security and Privacy (SP)</em>, 2023, 页 1220–1237. doi: <a href="https://doi.org/10.1109/SP46215.2023.10179415">10.1109/SP46215.2023.10179415</a>.</div>
</div>
<div id="ref-intelReverseCacheAddress" class="csl-entry" role="listitem">
<div class="csl-left-margin">[74] </div><div class="csl-right-inline">C. Maurice, N. Le Scouarnec, C. Neumann, O. Heen, 和 A. Francillon, <span>《<span>Reverse Engineering Intel Last-Level Cache Complex Addressing Using Performance Counters</span>》</span>, 收入 <em>Research in Attacks, Intrusions, and Defenses</em>, H. Bos, F. Monrose, 和 G. Blanc, 编, Cham: Springer International Publishing, 2015, 页 48–65.</div>
</div>
<div id="ref-intelReverseCacheSlice" class="csl-entry" role="listitem">
<div class="csl-left-margin">[75] </div><div class="csl-right-inline">G. Irazoqui, T. Eisenbarth, 和 B. Sunar, <span>《<span>Systematic Reverse Engineering of Cache Slice Selection in Intel Processors</span>》</span>, 收入 <em>2015 Euromicro Conference on Digital System Design</em>, 2015, 页 629–636. doi: <a href="https://doi.org/10.1109/DSD.2015.56">10.1109/DSD.2015.56</a>.</div>
</div>
<div id="ref-reverseNoc" class="csl-entry" role="listitem">
<div class="csl-left-margin">[76] </div><div class="csl-right-inline">J. Ahn <em>等</em>, <span>《<span>Network-on-Chip Microarchitecture-based Covert Channel in GPUs</span>》</span>, 收入 <em>MICRO-54: 54th Annual IEEE/ACM International Symposium on Microarchitecture</em>, 收入 MICRO ’21. New York, NY, USA: Association for Computing Machinery, 2021, 页 565–577. doi: <a href="https://doi.org/10.1145/3466752.3480093">10.1145/3466752.3480093</a>.</div>
</div>
<div id="ref-UncoveringNOC" class="csl-entry" role="listitem">
<div class="csl-left-margin">[77] </div><div class="csl-right-inline">Z. Jin <em>等</em>, <span>《´Uncovering Real GPU NoC Characteristics: Implications on Interconnect Architecture》</span>, doi: <a href="https://doi.org/10.1109/MICRO61859.2024.00070">10.1109/MICRO61859.2024.00070</a>.</div>
</div>
<div id="ref-reverseMshrPRT" class="csl-entry" role="listitem">
<div class="csl-left-margin">[78] </div><div class="csl-right-inline">A. Lashgar, E. Salehi, 和 A. Baniasadi, <span>《<span>A Case Study in Reverse Engineering GPGPUs: Outstanding Memory Handling Resources</span>》</span>, <em>SIGARCH Comput. Archit. News</em>, 卷 43, 期 4, 页 15–21, 4月 2016, doi: <a href="https://doi.org/10.1145/2927964.2927968">10.1145/2927964.2927968</a>.</div>
</div>
<div id="ref-voltaCaches" class="csl-entry" role="listitem">
<div class="csl-left-margin">[79] </div><div class="csl-right-inline">M. Khairy, J. Akshay, T. Aamodt, 和 T. G. Rogers, <span>《<span>Exploring Modern GPU Memory System Design Challenges through Accurate Modeling</span>》</span>, 2018, 载于: <a href="http://arxiv.org/abs/1810.07269 http://dx.doi.org/10.1109/ISCA45697.2020.00047">http://arxiv.org/abs/1810.07269 http://dx.doi.org/10.1109/ISCA45697.2020.00047</a></div>
</div>
<div id="ref-dissecTensorCoresVolta1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[80] </div><div class="csl-right-inline">S. Markidis, S. Chien, E. Laure, I. Peng, 和 J. S. Vetter, <span>《<span>NVIDIA Tensor Core Programmability, Performance &amp; Precision</span>》</span>, 收入 <em>2018 IEEE International Parallel and Distributed Processing Symposium Workshops (IPDPSW)</em>, Los Alamitos, CA, USA: IEEE Computer Society, 5月 2018, 页 522–531. doi: <a href="https://doi.org/10.1109/IPDPSW.2018.00091">10.1109/IPDPSW.2018.00091</a>.</div>
</div>
<div id="ref-dissecTensorCoresVolta2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[81] </div><div class="csl-right-inline">M. Martineau, P. Atkinson, 和 S. McIntosh-Smith, <span>《<span>Benchmarking the NVIDIA V100 GPU and Tensor Cores</span>》</span>, 收入 <em>Euro-Par 2018: Parallel Processing Workshops: Euro-Par 2018 International Workshops, Turin, Italy, August 27-28, 2018, Revised Selected Papers</em>, Berlin, Heidelberg: Springer-Verlag, 2019, 页 444–455. doi: <a href="https://doi.org/10.1007/978-3-030-10549-5_35">10.1007/978-3-030-10549-5_35</a>.</div>
</div>
<div id="ref-dissecTensorCoresTuringVolta1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[82] </div><div class="csl-right-inline">M. A. Raihan, N. Goli, 和 T. M. Aamodt, <span>《<span>Modeling Deep Learning Accelerator Enabled GPUs</span>》</span>, 收入 <em>2019 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)</em>, 2019, 页 79–92. doi: <a href="https://doi.org/10.1109/ISPASS.2019.00016">10.1109/ISPASS.2019.00016</a>.</div>
</div>
<div id="ref-dissecTensorCoresTuringVolta2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[83] </div><div class="csl-right-inline">D. Yan, W. Wang, 和 X. Chu, <span>《<span>Demystifying Tensor Cores to Optimize Half-Precision Matrix Multiply</span>》</span>, 收入 <em>2020 IEEE International Parallel and Distributed Processing Symposium (IPDPS)</em>, 2020, 页 634–643. doi: <a href="https://doi.org/10.1109/IPDPS47924.2020.00071">10.1109/IPDPS47924.2020.00071</a>.</div>
</div>
<div id="ref-dissecTensorCoresAmpere1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[84] </div><div class="csl-right-inline">M. Fasi, N. J. Higham, M. Mikaitis, 和 S. Pranesh, <span>《<span>Numerical behavior of NVIDIA tensor cores</span>》</span>, <em>PeerJ Computer Science</em>, 卷 7, 页 1–19, 2月 2021, doi: <a href="https://doi.org/10.7717/PEERJ-CS.330/FIG-1">10.7717/PEERJ-CS.330/FIG-1</a>.</div>
</div>
<div id="ref-dissecTensorCoresAmpere2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[85] </div><div class="csl-right-inline">W. Sun, A. Li, T. Geng, S. Stuijk, 和 H. Corporaal, <span>《<span>Dissecting Tensor Cores via Microbenchmarks: Latency, Throughput and Numeric Behaviors</span>》</span>, <em>IEEE Transactions on Parallel and Distributed Systems</em>, 卷 34, 期 1, 页 246–261, 2023, doi: <a href="https://doi.org/10.1109/TPDS.2022.3217824">10.1109/TPDS.2022.3217824</a>.</div>
</div>
<div id="ref-tunnelsTLB" class="csl-entry" role="listitem">
<div class="csl-left-margin">[86] </div><div class="csl-right-inline">Z. Zhang, T. Allen, F. Yao, X. Gao, 和 R. Ge, <span>《<span>TunneLs for Bootlegging: Fully Reverse-Engineering GPU TLBs for Challenging Isolation Guarantees of NVIDIA MIG</span>》</span>, 收入 <em>Proceedings of the 2023 ACM SIGSAC Conference on Computer and Communications Security</em>, 收入 CCS ’23. New York, NY, USA: Association for Computing Machinery, 2023, 页 960–974. doi: <a href="https://doi.org/10.1145/3576915.3616672">10.1145/3576915.3616672</a>.</div>
</div>
<div id="ref-reverseTX2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[87] </div><div class="csl-right-inline">T. Amert, N. Otterness, M. Yang, J. H. Anderson, 和 F. D. Smith, <span>《<span>GPU Scheduling on the NVIDIA TX2: Hidden Details Revealed</span>》</span>, 收入 <em>2017 IEEE Real-Time Systems Symposium (RTSS)</em>, 2017, 页 104–115. doi: <a href="https://doi.org/10.1109/RTSS.2017.00017">10.1109/RTSS.2017.00017</a>.</div>
</div>
<div id="ref-demystifyingGPU" class="csl-entry" role="listitem">
<div class="csl-left-margin">[88] </div><div class="csl-right-inline">H. Wong, M.-M. Papadopoulou, M. Sadooghi-Alvandi, 和 A. Moshovos, <span>《<span>Demystifying GPU microarchitecture through microbenchmarking</span>》</span>, 收入 <em>2010 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)</em>, 2010, 页 235–246. doi: <a href="https://doi.org/10.1109/ISPASS.2010.5452013">10.1109/ISPASS.2010.5452013</a>.</div>
</div>
<div id="ref-amdGap1" class="csl-entry" role="listitem">
<div class="csl-left-margin">[89] </div><div class="csl-right-inline">A. Gutierrez <em>等</em>, <span>《<span><span style="color: darkerGreen">Lost in Abstraction: Pitfalls of Analyzing GPUs at the Intermediate Language Level</span></span>》</span>, 收入 <em>2018 IEEE International Symposium on High Performance Computer Architecture (HPCA)</em>, 2018, 页 608–619. doi: <a href="https://doi.org/10.1109/HPCA.2018.00058">10.1109/HPCA.2018.00058</a>.</div>
</div>
<div id="ref-amdGap2" class="csl-entry" role="listitem">
<div class="csl-left-margin">[90] </div><div class="csl-right-inline">C. Jamieson, A. Chandrashekar, I. McDougall, 和 M. D. Sinclair, <span>《<span><span style="color: darkerGreen">gem5 GPU Accuracy Profiler (GAP)</span></span>》</span>, 收入 <em>4th gem5 Users’ Workshop</em>, 2022.</div>
</div>
<div id="ref-amdGap3" class="csl-entry" role="listitem">
<div class="csl-left-margin">[91] </div><div class="csl-right-inline">V. Ramadas, D. Kouchekinia, N. Osuji, 和 M. D. Sinclair, <span>《<span><span style="color: darkerGreen">Closing the Gap: Improving the Accuracy of gem5’s GPU Models</span></span>》</span>, 收入 <em>5th gem5 Users’ Workshop</em>, 2023.</div>
</div>
<div id="ref-amdGap4" class="csl-entry" role="listitem">
<div class="csl-left-margin">[92] </div><div class="csl-right-inline">V. Ramadas, D. Kouchekinia, 和 M. D. Sinclair, <span>《<span><span style="color: darkerGreen">Further Closing the GAP: Improving the Accuracy of gem5’s GPU Models</span></span>》</span>, 收入 <em>6th Young Architects’ (YArch) Workshop</em>, 2024.</div>
</div>
<div id="ref-intelGPUs" class="csl-entry" role="listitem">
<div class="csl-left-margin">[93] </div><div class="csl-right-inline">P. Gera, H. Kim, H. Kim, S. Hong, V. George, 和 C.-K. Luk, <span>《<span><span style="color: darkerGreen">Performance Characterisation and Simulation of Intel’s Integrated GPU Architecture</span></span>》</span>, 收入 <em>2018 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS)</em>, Los Alamitos, CA, USA: IEEE Computer Society, 4月 2018, 页 139–148. doi: <a href="https://doi.org/10.1109/ISPASS.2018.00027">10.1109/ISPASS.2018.00027</a>.</div>
</div>
<div id="ref-HardwareAwareCompilation" class="csl-entry" role="listitem">
<div class="csl-left-margin">[94] </div><div class="csl-right-inline">A. Shrivastava 和 J. Cai, <span>《Hardware-aware compilation》</span>, 收入 <em>Handbook of Hardware/Software Codesign</em>, Netherlands: Springer Netherlands, 2017, 页 795–827. doi: <a href="https://doi.org/10.1007/978-94-017-7267-9_26">10.1007/978-94-017-7267-9_26</a>.</div>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">脚注</h2>

<ol>
<li id="fn1"><p>Ampere 允许 FP32 操作在 FP32 与 INT32 执行单元上执行<span class="citation" data-cites="amperePaper"><a href="#ref-amperePaper" role="doc-biblioref">[21]</a></span>，因此两个连续 FP32 指令之间不会因执行单元冲突产生气泡。<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "已复制");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "已复制");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/sadsock\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 SadSock</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>